Revert of Fall back on stencil clip when SW mask fails to allocate (patchset #1 id:1 of https://codereview.chromium.org/2469753002/ )
Reason for revert:
Build failure: src/gpu/GrClipStackClip.cpp:303:41: error: use of undeclared identifier 'renderTargetContext'

Original issue's description:
> Fall back on stencil clip when SW mask fails to allocate
>
> When generating a SW clip mask, we didn't used to verify that the
> pixels had been successfully allocated. This would obviously crash
> when the allocation was not successful. This change checks the
> allocation first, and falls back on a stencil clip when it doesn't
> succeed.
>
> TBR=bsalomon@google.com
> BUG=656589
> GOLD_TRYBOT_URL= https://gold.skia.org/search?issue=2469753002
> NOTREECHECKS=true
> NOTRY=true
> NOPRESUBMIT=true
>
> Committed: https://skia.googlesource.com/skia/+/af9321799d99d3d6f4b77ff2bcea6ce87c97e134

TBR=csmartdalton@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=656589

Review-Url: https://codereview.chromium.org/2466363002