Revert "Retry enabling skcms on Android"
This reverts commit 05b5e40519ae18939867f8de5d48f7c7a173f745.

Reason for revert:

	BitmapColorSpaceTest.android.graphics.cts.BitmapColorSpaceTest.inColorSpaceP3ToSRGB (android.graphics.cts) 	06.949
 java.lang.AssertionError: expected:<67043583> but was:<117375231>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at android.graphics.cts.BitmapColorSpaceTest.verifyGetPixel(BitmapColorSpaceTest.java:301)
	at android.graphics.cts.BitmapColorSpaceTest.inColorSpaceP3ToSRGB(BitmapColorSpaceTest.java:612)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:148)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:764)

>>> hex(117375231)
'0x6ff00ff'
>>> hex(67043583)
'0x3ff00ff'

Original change's description:
> Retry enabling skcms on Android
> 
> Since we tried this last, DM has a direct skcms dependency
> via tests/ColorSpaceTest.cpp, so I've rearranged gn_to_bp.py slightly.
> 
> We need to keep our eyes out for BitmapRGBAF16Test.testGetPixel in CTS.
> 
> Change-Id: I3630bbebb4574522c43362c359d1a14da3bdd480
> Reviewed-on: https://skia-review.googlesource.com/124720
> Commit-Queue: Mike Klein <mtklein@google.com>
> Reviewed-by: Mike Klein <mtklein@google.com>

TBR=mtklein@chromium.org,mtklein@google.com,brianosman@google.com

Change-Id: Ib11393c427e9c5fea645de6e6e9a3034dcf06d02
No-Presubmit: true
No-Tree-Checks: true
No-Try: true