Revert "Add DSL PossibleExpression & PossibleStatement"
This reverts commit d42932a1b5b19098961b4837d54f75a52f278817.

Reason for revert: Broke CMake and SKQP builds.

E.g. https://logs.chromium.org/logs/skia/51ef0e1d4cc92f11/+/steps/Build_SKQP_apk_with_Docker/0/stdout

../../../src/sksl/dsl/DSLErrorHandling.h:18:37: error: use of undeclared identifier '__builtin_FILE'
    PositionInfo(const char* file = __builtin_FILE(), int line = __builtin_LINE())

Original change's description:
> Add DSL PossibleExpression & PossibleStatement
>
> These are currently unused, but in future CLs they will be used to
> capture line number information in DSL error handling.
>
> Change-Id: Ieee730e0ad8323043437972fedb5bec471c367e4
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/375069
> Reviewed-by: John Stiles <johnstiles@google.com>

TBR=brianosman@google.com,ethannicholas@google.com,johnstiles@google.com

Change-Id: Ibc4282384ed7c397b5b0999363fc742a1e115820
No-Presubmit: true
No-Tree-Checks: true
No-Try: true