Update patch set 8
Patch Set 8:

> Patch Set 8: Code-Review+1
> 
> I've also verified that we no longer build with 2015 (because of newer constexpr features)

Fails android bots because "python -c from gn import gn_to_bp" fails:


Generating JSON projects took 15ms
Done. Made 120 targets from 49 files in 67ms
Generating JSON projects took 5ms
Done. Made 56 targets from 39 files in 71ms
Generating JSON projects took 5ms
Done. Made 56 targets from 39 files in 51ms
ERROR at //gn/BUILDCONFIG.gn:128:29: Script returned non-zero exit code.
    win_toolchain_version = exec_script("//gn/highest_version_dir.py",
                            ^----------
Current dir: /tmp/tmpTIGZxe/
Command: python -- /mnt/pd0/checkouts/checkout_9/external/skia/gn/highest_version_dir.py dummy_version/Tools/MSVC [0-9]{2}\.[0-9]{2}\.[0-9]{5}
Returned 1.
stderr:

Traceback (most recent call last):
  File "/mnt/pd0/checkouts/checkout_9/external/skia/gn/highest_version_dir.py", line 15, in <module>
    print sorted(filter(regex.match, os.listdir(dirpath)))[-1]
OSError: [Errno 2] No such file or directory: 'dummy_version/Tools/MSVC'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "gn/gn_to_bp.py", line 393, in <module>
    js_win          = gn_to_bp_utils.GenerateJSONFromGN(gn_args_win)
  File "gn/gn_to_bp_utils.py", line 26, in GenerateJSONFromGN
    '--ide=json'])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/tmp/tmpTIGZxe', '--args=is_official_build=true skia_enable_fontmgr_android=false skia_enable_fontmgr_custom=false skia_enable_fontmgr_custom_empty=true skia_enable_fontmgr_win=false skia_enable_fontmgr_win_gdi=false skia_enable_gpu=false skia_include_multiframe_procs=false skia_use_fixed_gamma_text=true skia_use_fontconfig=false skia_use_fonthost_mac=false skia_use_freetype=true skia_use_libheif=false skia_use_vulkan=false skia_use_xps=false target_cpu="none" target_os="win" win_sdk_version="dummy_version" win_vc="dummy_version"', '--ide=json']' returned non-zero exit status 1

Patch-set: 8
CC: Gerrit User 5145 <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>