Revert "Add third_party/cityhash"
This reverts commit b06e7c291aec5a3713f32a70635b8135e755a5d1.

Reason for revert: Reason for revert: Debian10 build broken
../../../../../../skia/third_party/cityhash/city.cc:515:10: fatal error: 'citycrc.h' file not found
#include <citycrc.h>
         ^~~~~~~~~~~

Original change's description:
> Add third_party/cityhash
>
> This is a clone of https://github.com/google/cityhash,
> trimmed down to the just the bits we need, similar to
> chromium's base/third_party/cityhash.
>
> Minor tweaks to the source code:
> - Removed include of config.h
> - Changed include <city.h> to "city.h"
> - Renamed COPYING to LICENSE
>
> Change-Id: If745e77b7d3520202957d4e97c1d6c2ac773b4d0
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/698457
> Reviewed-by: John Stiles <johnstiles@google.com>
> Commit-Queue: Brian Osman <brianosman@google.com>

Change-Id: I9d50550699ed6ca3adf519b6daacb1e95a20127c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/698757
Auto-Submit: John Stiles <johnstiles@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>