Add missing include
* This should resolve the Android roller failure:
```
external/skia/src/codec/SkCrabbyAvifCodec.cpp:246:29: error: incomplete type 'SkCodecs::ColorProfile' named in nested name specifier
  246 |         profile = SkCodecs::ColorProfile::MakeICCProfile(std::move(icc));
```

Change-Id: Ie68c467282ba2c7d8f1ae2e8f6ea06cc898bb4be
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1116401
Reviewed-by: Robert Phillips <robertphillips@google.com>
Commit-Queue: Nicolette Prevost <nicolettep@google.com>
Commit-Queue: Christopher Cameron <ccameron@google.com>
Reviewed-by: Christopher Cameron <ccameron@google.com>