Update patch set 4
Patch Set 4:

I think this causes the Android compile bots to fail (and eventually the roller should fail as well) with:

FAILED: out/soong/.intermediates/external/skia/skia_dm/android_arm_armv7-a-neon_core/obj/external/skia/gm/fiddle.o
PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r353983d/bin/clang++ -c -Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-null-dereference -Iexternal/skia -Iexternal/skia/include/third_party/skcms -Iexternal/skia/include/third_party/vulkan -Iexternal/skia/modules/skottie/include -Iexternal/skia/modules/skottie/utils -Iexternal/skia/modules/sksg/include -Iexternal/skia -mthumb -Os -fomit-frame-pointer -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -msoft-float -march=armv7-a -mfloat-abi=softfp -mfpu=neon  -D__LIBANDROIDICU_API__=1 -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Iexternal/googletest/googletest/include -Iframeworks/native/libs/arect/include -Iexternal/sfntly/cpp/src -Iexternal/webp/include -Iexternal/skia -Iexternal/skia/include/android -Iexternal/skia/include/atlastext -Iexternal/skia/include/c -Iexternal/skia/include/codec -Iexternal/skia/include/config -Iexternal/skia/include/core -Iexternal/skia/include/docs -Iexternal/skia/include/effects -Iexternal/skia/include/encode -Iexternal/skia/include/gpu -Iexternal/skia/include/pathops -Iexternal/skia/include/ports -Iexternal/skia/include/svg -Iexternal/skia/include/utils -Iexternal/skia/include/utils/mac -Iexternal/skia/modules/skottie/include -Iexternal/skia/modules/sksg/include -Iexternal/skia/modules/skshaper/include -Iexternal/skia/android -Iexternal/vulkan-headers/include -Iexternal/icu/libandroidicu/include -Iexternal/dng_sdk/source -Iexternal/expat/lib -Iexternal/freetype/include -Iexternal/libjpeg-turbo -Isystem/core/liblog/include -Iexternal/piex -Iexternal/libpng -Iexternal/zlib -Iframeworks/native/libs/binder/include -Isystem/core/base/include -Isystem/core/libcutils/include -Isystem/core/libutils/include -Isystem/core/libbacktrace/include -Isystem/core/libsystem/include -Isystem/core/libprocessgroup/include -Iout/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_arm_armv7-a-neon_core_shared/gen/aidl -Iframeworks/native/opengl/libs/EGL/include -Iframeworks/native/opengl/include -Iframeworks/av/media/libheif/include -Iframeworks/native/libs/nativewindow/include -Iframeworks/native/libs/nativewindow/include-private -Iframeworks/native/libs/nativebase/include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Ibionic/libc/include -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -Ilibnativehelper/include_jni -Wall -Werror -Wno-implicit-fallthrough -Wno-unused-parameter -Wno-unused-variable -target armv7a-linux-androideabi10000 -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -fPIE -DGTEST_HAS_STD_STRING -DGTEST_OS_LINUX_ANDROID -D_USING_LIBCXX -std=gnu++17 -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden -fno-rtti  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF out/soong/.intermediates/external/skia/skia_dm/android_arm_armv7-a-neon_core/obj/external/skia/gm/fiddle.o.d -o out/soong/.intermediates/external/skia/skia_dm/android_arm_armv7-a-neon_core/obj/external/skia/gm/fiddle.o external/skia/gm/fiddle.cpp
external/skia/gm/fiddle.cpp:9:10: fatal error: 'skia.h' file not found
#include "skia.h"
         ^~~~~~~~
1 error generated.

Patch-set: 4
CC: Gerrit User 5145 <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>