Update patch set 1
Patch Set 1:

(3 comments)

> Patch Set 1:
> 
> (1 comment)
> 
> "dm --match Gif" passes. "dm --match Codec" fails, but it also failed before this CL. I'm not sure what the plan is to get back to all-tests-green (with skia_use_wuffs=true). :-/

I assume all the failures are in 565? (I think after https://skia-review.googlesource.com/c/176582 it should be more obvious?)

My plan is to add color correction after this, which will handle 565 and pass those tests.

I was going to test this and find out, but for some reason I'm getting the following linking error:

undefined reference to `wuffs_gif__decoder__frame_dirty_rect'

I'm still using wuffs commit f51c71b72cfc3ce3515d1196eb78f0a64c9955ff, which I last updated in https://skia-review.googlesource.com/c/175900. I don't see what's changed to give me this error. (I even tried syncing Skia back to that commit, which used to work for me, and I still see that linking error.)

Patch-set: 1
Reviewer: Gerrit User 5255 <5255@5086850b-e599-37d2-8ec8-ff16aeccbf02>