Update patch set 7
Patch Set 7:

This causes asserts on ToT chrome for me:

[1:10:1025/173704.994823:INFO:SkTo.h(14)] ../../third_party/skia/include/gpu/../private/SkTo.h:14: fatal error: "assert(SkTFitsIn<D>(s))"

#6 0x7fd0410d1608 sk_abort_no_print()
#7 0x7fd04119aa4f _ZZ4SkToItiET_T0_ENKUlvE_clEv
#8 0x7fd04119aa8e SkTo<>()
#9 0x7fd04172ae2c SkPackedGlyphID::code()
#10 0x7fd04172a289 SkGlyph::getGlyphID()
#11 0x7fd041725861 SkScalerContext_FreeType::generateMetrics()
#12 0x7fd041a2b6d4 SkScalerContext::getMetrics()
#13 0x7fd041a0e5a5 SkStrikeServer::SkGlyphCacheState::writePendingGlyphs()
#14 0x7fd041a0e02e SkStrikeServer::writeStrikeData()
#15 0x7fd02a4b2788 gpu::raster::ClientFontManager::Serialize()
#16 0x7fd02a4c94f6 gpu::raster::RasterImplementation::PaintOpSerializer::SendSerializedData()
#17 0x7fd02a4c5c4e gpu::raster::RasterImplementation::RasterCHROMIUM()
#18 0x7fd036e39858 cc::(anonymous namespace)::RasterizeSourceOOP()
#19 0x7fd036e391cd cc::GpuRasterBufferProvider::PlaybackOnWorkerThreadInternal()
#20 0x7fd036e377d3 cc::GpuRasterBufferProvider::PlaybackOnWorkerThread()
#21 0x7fd036e3752b cc::GpuRasterBufferProvider::RasterBufferImpl::Playback()

Repro'd on Linux via: ninja -C out/Debug chrome && out/Debug/chrome --enable-gpu-rasterization --enable--oop-rasterization http://google.com

Patch-set: 7
CC: Gerrit User 6595 <6595@5086850b-e599-37d2-8ec8-ff16aeccbf02>