Mark ~LuaView as override.
Newer clang versions report

../../samplecode/SampleLua.cpp:44:13: error:
'~LuaView' overrides a destructor but is not marked 'override'
[-Werror,-Winconsistent-missing-destructor-override]

Change-Id: I6f3e69482a79e9580e51b957fff06e6d4d270735