Fix build errors due to SkShadowFlags enum
* Removed SK_API decoration on the enum, due to an error on Windows that
  looks like this:

  In file included from ../../third_party/skia/src/utils/SkShadowUtils.cpp:8:
../../third_party/skia\include/utils/SkShadowUtils.h(23,6): error: 'dllexport' attribute only applies to functions, variables, classes, and Objective-C interfaces [-Werror,-Wignored-attributes]
23 | enum SK_API SkShadowFlags {
|      ^


* Deleted include/private/SkShadowFlags.h, which was removed from the
  build but still left in the tree.

Change-Id: Ie841c65507f4332be6a16396cb9eb867a00e932f
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/753381
Reviewed-by: Greg Daniel <egdaniel@google.com>
Reviewed-by: Kevin Lubick <kjlubick@google.com>
Commit-Queue: Arman Uguray <armansito@google.com>