Revert "Remove (now-dead) SK_LEGACY_SWEEP_GRADIENT code"
This reverts commit 04d22c04838fb312aa5ecc770299aff31076e7e3.

Reason for revert: Android roll?
junit.framework.AssertionFailedError: res/drawable/vector_icon_gradient_1.xml: totalDiffPixelCount is 123


Original change's description:
> Remove (now-dead) SK_LEGACY_SWEEP_GRADIENT code
> 
> Behold the first raster pipeline-only gradient!
> 
> Change-Id: Ib6f53224e4ff9506aafdae1d2303102fc5235dfc
> Reviewed-on: https://skia-review.googlesource.com/17982
> Commit-Queue: Mike Klein <mtklein@chromium.org>
> Reviewed-by: Mike Klein <mtklein@chromium.org>
> 

TBR=mtklein@chromium.org,mtklein@google.com,herb@google.com,fmalita@chromium.org,reed@google.com
No-Presubmit: true
No-Tree-Checks: true
No-Try: true

Change-Id: I328585f5412068f4eff1d0a2a6083cb4c1a3c078