Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Do you mind taking a look at the GCC failures here?  Briefly it's something like this,
> 
>     static int bar(int x) { ... }
>     static int baz(int x) { ... }
> 
>     template <int (*fn)(int)>
>     int foo(int x) {
>         constexpr bool twice = fn == bar;
>  
>         x = fn(x);
>         if (twice) {
>             x = fn(x);
>         }
>         return x;
>     } 
> 
> but GCC doesn't think `fn == bar` is a constant expression, while MSVC and Clang do.

Full repro...

~ $ cat foo.cc
static int bar(int x) { return x+x; }
static int baz(int x) { return x*x; }

template <int (*fn)(int)>
int foo(int x) {
    constexpr bool twice = fn == bar;

    x = fn(x);
    if (twice) {
        x = fn(x);
    }
    return x;
}

int go(int);
int go(int x) {
    if (x < 7) { return foo<bar>(x); }
    return foo<baz>(x);
}
~ $ clang++ -Werror -Weverything -Wno-c++98-compat -c foo.cc
~ $ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~ $ g++ -c foo.cc
foo.cc: In instantiation of ‘int foo(int) [with int (* fn)(int) = baz]’:
foo.cc:18:22:   required from here
foo.cc:6:31: error: ‘(baz == bar)’ is not a constant expression
     constexpr bool twice = fn == bar;
                            ~~~^~~~~~

Patch-set: 1
Reviewer: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Label: Commit-Queue=0