Revert "Turn on exceptions in test tools."
This reverts commit c667dff58dc4b16faf30c34e98a118c6a1c1f987.

Reason for revert: breaking the Android roll: external/skia/tests/ExceptionTest.cpp:14:9: error: cannot use 'throw' with exceptions disabled
        throw 42;
        ^
external/skia/tests/ExceptionTest.cpp:13:5: error: cannot use 'try' with exceptions disabled
    try {
    ^

Original change's description:
> Turn on exceptions in test tools.
> 
> This allows us to test things that, e.g., throw std::bad_alloc.
> 
> Change-Id: I6409159b89f1d93d403b1a1f40539cf2531a8b68
> Reviewed-on: https://skia-review.googlesource.com/34982
> Reviewed-by: Herb Derby <herb@google.com>
> Commit-Queue: Mike Klein <mtklein@chromium.org>

TBR=mtklein@chromium.org,herb@google.com

Change-Id: I3f9143eea694cd18d02223d4766afd34cd95aa81
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/35082
Reviewed-by: Leon Scroggins <scroggo@google.com>
Commit-Queue: Leon Scroggins <scroggo@google.com>