Revert "spanification: Add SK_UNSAFE_TODO in gpu/graphite (1/7)"
This reverts commit 2a685534004f400aab598ab05423cd64a4c9168d.

Reason for revert: Seems to be breaking the Chrome roll with:

../../third_party/skia/src/gpu/graphite/task/CopyTask.cpp:139:9: error: use of undeclared identifier 'SkLog'
  139 |         SKIA_LOG_E("Unable to copy between textures of different formats, src = %s, dst = %s",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  140 |                     TextureFormatName(srcFormat), TextureFormatName(dstFormat));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/skia/include/private/SkLog.h:39:30: note: expanded from macro 'SKIA_LOG_E'

Failure Link: <LINK TO FAILURE>

Original change's description:
> spanification: Add SK_UNSAFE_TODO in gpu/graphite (1/7)
>
> As part of the effort to enforce -Wunsafe-buffer-usage across Skia, this
> patch inserts SK_UNSAFE_TODO macro in targeted lines that trigger the
> warning in a subset of files in the gpu/graphite directory, and deletes
> their file level check exclusion in unsafe_buffers_mappings.
>
> Upcoming follow-up work includes:
> - Refactoring existing code to use safe constructs (e.g., spans).
> - Expanding enforcement across directories beyond gpu/graphite.
>
> This CL introduces no behavior changes.
>
> Automated via: https://paste.googleplex.com/4903479387226112
> Design doc: http://go/unsafe-buffer-skia
>
> Bug: b/565401613
> Change-Id: I066e76247aa5fdfc4b204b6b0301542d17b92f21
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1375836
> Reviewed-by: Michael Ludwig <michaelludwig@google.com>
> Auto-Submit: Francisco Ochoa <frankchavez@google.com>
> Commit-Queue: Michael Ludwig <michaelludwig@google.com>

Bug: b/565401613
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ib6dc42124a5ef2a4775fff54e551143804864c13
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1381656
Commit-Queue: Robert Phillips <robertphillips@google.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Robert Phillips <robertphillips@google.com>