Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: Ie18f865f3b7f5b0263db1e52b19cf6faa0500fdd
Subject: Android roll broke with a compilation error: frameworks/base/libs/hwui/jni/Shader.cpp:243:37: error: no matching function for call to 'get'     sk_sp<SkRuntimeEffect> effect = std::get<0>(result)
Branch: refs/heads/master
Status: new
Topic: 
Commit: 3ad2effd0457f1a7bb6fa600ffe8d820654097a9
Tag: autogenerated:gerrit:newPatchSet
Groups: 3ad2effd0457f1a7bb6fa600ffe8d820654097a9
CC: Gerrit User 9471 <9471@5086850b-e599-37d2-8ec8-ff16aeccbf02>
CC: Gerrit User 5555 <5555@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5005 <5005@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5631 <5631@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 11059 <11059@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Private: false
Work-in-progress: false
Revert-of: 367060
Attention: {"person_ident":"Gerrit User 5631 \u003c5631@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 5045 \u003c5045@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 11059 \u003c11059@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}