Update patch set 5
Patch Set 5:

The android framework compile bot is failing with:


"main.go:214 Error when compiling task with ID 5720404698071040: Could not prepare Skia checkout for compile: Error when running gn_to_bp: Failed to run gn_to_bp: Command exited with exit status 1: PATH=/mnt/pd0/checkouts/checkout_4/external/skia/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin python -c from gn import gn_to_bp; Stdout+Stderr:
ERROR at //third_party/vulkan/BUILD.gn:7:5: Assignment had no effect.
    defined(is_skia_standalone) && is_skia_standalone && !is_official_build
    ^----------------------------------------------------------------------
You set the variable "is_skia_dev_build" here and it was unused before it went
out of scope.
See //BUILD.gn:624:22: which caused the file to be included.
    public_deps += [ "third_party/vulkan" ]
                     ^-------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "gn/gn_to_bp.py", line 225, in <module>
    js = gn_to_bp_utils.GenerateJSONFromGN(gn_args)
  File "gn/gn_to_bp_utils.py", line 26, in GenerateJSONFromGN
    '--ide=json'])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/tmp/tmpOd8IzW', '--args=is_official_build=true skia_enable_skottie=false skia_enable_tools=true skia_use_libheif=true skia_use_vulkan=true skia_vulkan_header="Skia_Vulkan_Android.h" target_cpu="none" target_os="android"', '--ide=json']' returned non-zero exit status 1
"  
 timestamp:  "2018-05-21T15:35:58.084144347Z"  
}

Patch-set: 5
CC: Ravi Mistry <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>