Update patch set 5
Patch Set 5:

(1 comment)

This is much better, but for some reason with my local fonts enabled (without --nonativeFonts on my linux box) I'm still getting

../../modules/skparagraph/src/ParagraphImpl.cpp:842: fatal error: "assert(textRange.start <= fText.size() && textRange.end <= fText.size())"

Though I'm not sure how to reproduce that for you (at least --nonativeFonts is nicely reproducible). It might be worth landing this for now anyway since it seems to make more things work while we figure out how to reproduce my local assert.

Patch-set: 5
Reviewer: Gerrit User 5140 <5140@5086850b-e599-37d2-8ec8-ff16aeccbf02>