Update patch set 2
Patch Set 2:

I think Google3 roller is failing because something needs to be added to public.bzl :

In file included from third_party/skia/HEAD/tests/SkParagraphTest.cpp:4:
third_party/skia/HEAD/modules/skparagraph/src/ParagraphBuilderImpl.h:9:10: fatal error: 'FontCollection.h' file not found
#include "FontCollection.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
Error in child process '/usr/bin/xcrun'. 1

Patch-set: 2