Revert "Add [[nodiscard]] to Sk[I]Rect::intersect"
This reverts commit 51d7e221fef0346f4ea55f498abc0bade16d0d0c.

Reason for revert: This seems to be blocking the Android roll with:

out/soong/.intermediates/frameworks/base/libs/hwui/libhwui/android_x86_64_static/obj/frameworks/base/libs/hwui/jni/Graphics.o frameworks/base/libs/hwui/jni/Graphics.cpp
frameworks/base/libs/hwui/jni/Graphics.cpp:725:13: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  725 |             destination.intersect(SkRect::Make(mSkiaBitmap->info().bounds()));

Original change's description:
> Add [[nodiscard]] to Sk[I]Rect::intersect
>
> Bug: skia:11782
> Change-Id: Ib594256098e6e837364ea66cd185b7105c086044
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/589412
> Commit-Queue: Michael Ludwig <michaelludwig@google.com>
> Reviewed-by: Brian Osman <brianosman@google.com>

Bug: skia:11782
Change-Id: I81f281cc35cb9d1df71242e80ddaa6b981d64186
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/891776
Auto-Submit: Robert Phillips <robertphillips@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>