Update patch set 5
Patch Set 5:

This broke the flutter build:

https://chromium-swarm.appspot.com/task?id=3f7af74abd38cc10&refresh=10


../../flutter/lib/ui/painting/codec.cc:379:35: error: no member named 'kNone' in 'SkCodec'
    if (requiredFrame != SkCodec::kNone) {

Patch-set: 5
CC: Gerrit User 5085 <5085@5086850b-e599-37d2-8ec8-ff16aeccbf02>