Fix compile error with recent Rust toolchains in Rust PNG FFI
Looks like there is a build error when building with the Android Rust
toolchain:

```
error: cannot explicitly borrow within an implicitly-borrowing pattern
       --> external/skia/rust/png/FFI.rs:929:44
        |
    929 |         let Some(png::InterlaceInfo::Adam7(ref adam7info)) = self.last_interlace_info.as_ref()
        |                                            ^^^ explicit `ref` binding modifier not allowed when implicitly borrowing
```

This is likely due to the toolchain being more recent

BUG=502195264

Change-Id: I0442821337ddb7af96cf352d3a6d201a8e181296
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1277336
Reviewed-by: Florin Malita <fmalita@google.com>
Commit-Queue: Elliot Sisteron <elliotsisteron@google.com>