Update patch set 2
Patch Set 2:

Looks like this caused some android test failures: https://chromium-swarm.appspot.com/task?id=36b5a37d94deba10&refresh=10

../../../src/core/SkRasterPipeline.cpp:20: fatal error: "assert(stage != from_srgb)"

Patch-set: 2