workaround for failing GomaNoFallback bot
I think the bot is failing incorrectly (like, a Goma bug).  llimits.h is
in the same directory as lctype.c and this #include should be fine.
But, it just so happens we can work around this by defining
LUA_USE_CTYPE, bypassing this code that's causing trouble.

    [1778/2124] compile ../../../third_party/externals/lua/lctype.c
    FAILED: obj/third_party/externals/lua/lua.lctype.obj
    c:\b\s\w\ir\cache\goma\gomacc "c:\b\s\w\ir\clang_win/bin/clang-cl.exe"
            /nologo /showIncludes /FC @obj/third_party/externals/lua/lua.lctype.obj.rsp
            /c ../../../third_party/externals/lua/lctype.c
            /Foobj/third_party/externals/lua/lua.lctype.obj
            /Fd"obj/third_party/lua/lua_c.pdb"
    In file included from ../../../third_party/externals/lua/lctype.c:13:
    ../../../third_party/externals/lua/lctype.h(36,10):
    fatal error: 'llimits.h' file not found
        #include "llimits.h"
                 ^~~~~~~~~~~
    1 error generated.

Change-Id: I79b477bbe05cc31f7f15fe3cd43f22f28675f8c0