re-enable effect deserialization for flutter
I've got to figure this is the cause of the broken flutter roll:

    [ RUN      ] ParagraphTest.SimpleShadow
    ../../third_party/skia/src/core/SkWriteBuffer.cpp:238: fatal error: "assert(name)"
    ./flutter/testing/run_tests.sh: line 11: 13151 Trace/breakpoint trap   (core dumped) out/host_debug_unopt/txt_unittests --font-directory=flutter/third_party/txt/third_party/fonts

Change-Id: Idffbd203c9f790fd7613153d9f7973c7ad0a87a5