Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > > How can I trigger specific try bots other than the default set of git cl try with PolyGerrit?
> > 
> > I tried:
> > 
> > git cl try -b Build-Ubuntu-Clang-x86_64-Release-Fast_NoBuildbot -m fake_master.task_scheduler
> > ERROR: Access denied: User user:fmalita@chromium.org cannot add builds to bucket master.fake_master.task_scheduler
> 
> Try-
> "git cl try -b Build-Ubuntu-Clang-x86_64-Release-Fast -B skia.primary"

Thanks Ravi, that works.

MikeK: looks like the AVX2 SkNx<8, float> specialization is missing Load4.

Patch-set: 4
Label: Code-Review=0