Revert "[g3] Fix broken build."
This reverts commit a61407fe443e686b769f5f3e75951ec02822d079.

Reason for revert: still failing https://screenshot.googleplex.com/4B2BCe7PTvq8pJ3

Original change's description:
> [g3] Fix broken build.
>
> Potential fix for:
>
>     SkImage_RasterPinnable.cpp:10:10: fatal error: 'include/android/SkImageAndroid.h' file not found
>     #include "include/android/SkImageAndroid.h"
>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> Bug: skia:14227
> Change-Id: I848ddb55f7cfe46502ae1994a3b87b173e39c735
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/698239
> Reviewed-by: Kevin Lubick <kjlubick@google.com>
> Commit-Queue: Leandro Lovisolo <lovisolo@google.com>

Bug: skia:14227
Change-Id: Iadadbe7d5786428f3d39679c0486f3769ea23fc9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/698696
Commit-Queue: John Stiles <johnstiles@google.com>
Auto-Submit: John Stiles <johnstiles@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Break Glass <breakglass@skia.org>