GCC: set SkBitmap move constructor and assign operators noexcept
Chromium GCC build breaks in PDF Thumbnail, as it declares its move
constructor and assign operator noexcept with default implementation,
but SkBitmap is not declared as such.

Build error:
../../pdf/thumbnail.cc:116:1: error: function ‘chrome_pdf::Thumbnail::Thumbnail(chrome_pdf::Thumbnail&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
  116 | Thumbnail::Thumbnail(Thumbnail&& other) noexcept = default;
      | ^~~~~~~~~
../../pdf/thumbnail.cc:118:12: error: function ‘chrome_pdf::Thumbnail& chrome_pdf::Thumbnail::operator=(chrome_pdf::Thumbnail&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
  118 | Thumbnail& Thumbnail::operator=(Thumbnail&& other) noexcept = default;
      |            ^~~~~~~~~

Bug: chromium:819294
Change-Id: Icd1d27965d973bb01b37182961d9c48da59ed4cc