Revert "Return POD from generateMetrics() rather than mutate SkGlyph"
This reverts commit d76a9c3bb3fd5a08b9164cb99c252cb1be2e7c23.

Reason for revert: SkScalerContext_win_dw.cpp(2386): fatal error: "Bad format" in GM_textblobrandomfont on the windows nativefont bots

Original change's description:
> Return POD from generateMetrics() rather than mutate SkGlyph
>
> This is a step towards making scalercontext subclasses *not* friends.
> By returning a 'public' struct, we can hide write-access to fields
> on SkGlyph. Other CLs will follow to complete this transitions
> (e.g. generateImage will need to be tweaked).
>
> Bug: skia:14629
> Change-Id: I4bb65e1da7e4926a8b084e67fd478bbd9cfc21f3
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/727156
> Auto-Submit: Mike Reed <mike@reedtribe.org>
> Commit-Queue: Ben Wagner <bungeman@google.com>
> Reviewed-by: Ben Wagner <bungeman@google.com>

Bug: skia:14629
Change-Id: I218221b046cd051774f46e5b71202089661166c6
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/730041
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Michael Ludwig <michaelludwig@google.com>