Revert "redirect SKGPU_LOG macros to SKIA_LOG"
This reverts commit e45bbba82ed749e1e175ba0adc5e6120f9f7401c.

Reason for revert: Breaking roll into Android

external/skia/src/gpu/graphite/ReadSwizzle.h:38:9: error: invalid operands to binary expression ('SkLogPriority' and 'skgpu::graphite::LogPriority')
   38 |         SKGPU_LOG_W("%s is an unsupported read swizzle. Defaulting to RGBA.\n",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   39 |                     swizzle.asString().data());
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
external/skia/src/gpu/graphite/Log.h:18:31: note: expanded from macro 'SKGPU_LOG_W'
   18 | #define SKGPU_LOG_W(fmt, ...) SKIA_LOG(SkLogPriority::kWarning, "[graphite] " fmt, ##__VA_ARGS__)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/skia/include/private/base/SkLog.h:43:32: note: expanded from macro 'SKIA_LOG'
   43 |         if constexpr (priority <= SKIA_LOWEST_ACTIVE_LOG_PRIORITY) {           \
      |                       ~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> redirect SKGPU_LOG macros to SKIA_LOG
>
> Change-Id: I66f61920ccf75fb79d5116839c84c60f53c8b97d
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1158717
> Reviewed-by: Noelle Scobie <nscobie@google.com>
> Commit-Queue: Jorge Betancourt <jmbetancourt@google.com>

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I2dde044060b8d7a85b87a6f8916338b2bd03ef67
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1162636
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>