Revert "[vulkan] Apply RelaxedPrecision to special intrinsics"
Revert submission 996937

Reason for revert: reverting due to nVidia internal compiler errors

	start vk gm  ycbcrimage
NVVM compilation failed: 1
Vulkan warning [Driver]: code: 2: CreatePipeline: failed to compile internal representation
Vulkan warning [Driver]: code: 2: CreatePipeline: unexpected compilation failure
Vulkan warning [Driver]: code: 2: CreateGraphicsPipeline: unexpected failure compiling SPIR-V shader: 0x725a6ee07d269c1f
../../../../../../skia/src/gpu/ganesh/vk/GrVkPipeline.cpp(597): fatal error: "check(VK_SUCCESS == err || VK_ERROR_DEVICE_LOST == err)"

Reverted changes: /q/submissionid:996937

Change-Id: I8969cfd0ac6f0236b3f6e7dbcb6e288b7b6e970c
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/998878
Commit-Queue: Michael Ludwig <michaelludwig@google.com>
Reviewed-by: Nicolette Prevost <nicolettep@google.com>