Update patch set 11
Patch Set 11:

I think this CL broke Android roller:

external/skia/src/core/SkCanvas.cpp
external/skia/src/core/SkCanvas.cpp:675:36: error: no matching constructor for initialization of 'SkBitmapDevice'
sk_sp<SkBaseDevice> device(new SkBitmapDevice(tmp, fProps, nullptr));
^ ~~~~~~~~~~~~~~~~~~~~
external/skia/src/core/SkBitmapDevice.h:57:5: note: candidate constructor not viable: requires 4 arguments, but 3 were provided
SkBitmapDevice(const SkBitmap& bitmap, const SkSurfaceProps& surfaceProps,
^
external/skia/src/core/SkBitmapDevice.h:43:5: note: candidate constructor not viable: requires single argument 'bitmap', but 3 arguments were provided
SkBitmapDevice(const SkBitmap& bitmap);
^
external/skia/src/core/SkBitmapDevice.h:36:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
class SkBitmapDevice : public SkBaseDevice {
^
1 error generated.

Patch-set: 11
CC: Stan Iliev <5656@5086850b-e599-37d2-8ec8-ff16aeccbf02>