Update patch set 6
Patch Set 6:

Not sure either. "git cl upload" after an initial promising start at the end outputted messages like this:

  ...
  [W2017-05-26 18:57:08,293 17108 140647260182336 gerrit_util.py] A transient error occurred while querying skia-review.googlesource.com:
  HTTP/1.1 404 Not Found
  [W2017-05-26 18:57:02,164 17108 140647260182336 gerrit_util.py] ... will retry 2 more times.
  ...
    File "/home/matfra01/local/opt/depot_tools/gerrit_util.py", line 643, in SetCommitMessage
      raise e
  gerrit_util.GerritError: Received unexpected http status while editing message in change 16520

The net effect was that the patch was uploaded but without updating the commit message. The strange title after the manual edit was due to leftover trailing spaces, which I could spot by switching to the old dear Gerrit UI. Somehow PolyGerrit doesn't seem to show trailing spaces, while the old UI nicely highlights them in red :)

Patch-set: 6
Reviewer: Matteo Franchin <6920@5086850b-e599-37d2-8ec8-ff16aeccbf02>