Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: I9d679013cb275dc80aaaa977b7f1f4da31f36d1e
Subject: Revert "Android roll broke with a compilation error:"
Branch: refs/heads/master
Status: new
Topic: 
Commit: c7db77b37899d856832ff234e2fb93c4d36cb518
Tag: autogenerated:gerrit:newPatchSet
Groups: c7db77b37899d856832ff234e2fb93c4d36cb518
CC: Gerrit User 9471 <9471@5086850b-e599-37d2-8ec8-ff16aeccbf02>
CC: Gerrit User 5555 <5555@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5005 <5005@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5631 <5631@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5656 <5656@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Private: false
Work-in-progress: false
Revert-of: 368616
Attention: {"person_ident":"Gerrit User 5631 \u003c5631@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 5656 \u003c5656@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 5045 \u003c5045@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}