Update patch set 3
Patch Set 3:

It looks like this CL was causing the following asserts on the following bots:

Win10 Vulkan
NUC6i5SYK Ubuntu16_Vulkan
PixelXL Android_Vulkan
nVidia Shield Android_Vulkan
Nexus6p Android_Vulkan

14.4m		unit test  TessellatingPathRendererTests
../../../src/gpu/vk/GrVkCommandBuffer.cpp:649: fatal error: "assert(dataSize <= 65536)"

Patch-set: 3
CC: Robert Phillips <5230@5086850b-e599-37d2-8ec8-ff16aeccbf02>