Update patch set 1
Patch Set 1:

First level error:
error adding symbols: DSO missing from command line

I moved around libskia.a to go first and that fixed first level error, but still leaves many link errors like:
/SRC/src/codec/SkWebpCodec.cpp:268: undefined reference to `WebPDemuxGetFrame'
libskia.a(SkWebpCodec.cpp.o): In function `SkWebpCodec::onGetFrameCount()':
/SRC/include/codec/../private/SkTemplates.h:50: undefined reference to `WebPDemuxReleaseIterator'
libthird_party__zlib.a(crc32.c.o): In function `Cr_z_crc_reset':
/SRC/third_party/externals/zlib/crc32.c:503: undefined reference to `Cr_z_x86_cpu_enable_simd'
/SRC/third_party/externals/zlib/crc32.c:504: undefined reference to `Cr_z_crc_fold_init'

Patch-set: 1
CC: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>
CC: Gerrit User 5140 <5140@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Reviewer: Gerrit User 5395 <5395@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Work-in-progress: false