[bazel] Add --expunge back in before BazelTest
For reasons currently unknown, running CanvasKit tests would
start to fail as if it could not find certain npm files:

ERROR: /mnt/pd0/s/w/ir/skia/modules/canvaskit/BUILD.bazel:369:11: Middleman _middlemen/modules_Scanvaskit_Scanvaskit_Ujs_Utests-runfiles failed: missing input file 'external/npm/node_modules/karma-chrome-launcher/CHANGELOG.md', owner: '@npm//:node_modules/karma-chrome-launcher/CHANGELOG.md'
ERROR: /mnt/pd0/s/w/ir/skia/modules/canvaskit/BUILD.bazel:369:11: Middleman _middlemen/modules_Scanvaskit_Scanvaskit_Ujs_Utests-runfiles failed: missing input file 'external/npm/node_modules/karma-chrome-launcher/LICENSE', owner: '@npm//:node_modules/karma-chrome-launcher/LICENSE'
ERROR: /mnt/pd0/s/w/ir/skia/modules/canvaskit/BUILD.bazel:369:11: Middleman _middlemen/modules_Scanvaskit_Scanvaskit_Ujs_Utests-runfiles failed: missing input file 'external/npm/node_modules/karma-chrome-launcher/README.md', owner: '@npm//:node_modules/karma-chrome-launcher/README.md'
ERROR: /mnt/pd0/s/w/ir/skia/modules/canvaskit/BUILD.bazel:369:11: Middleman _middlemen/modules_Scanvaskit_Scanvaskit_Ujs_Utests-runfiles failed: missing input file 'external/npm/node_modules/karma-chrome-launcher/examples/simple/index.spec.js', owner: '@npm//:node_modules/karma-chrome-launcher/examples/simple/index.spec.js'
...

We saw this before and I thought updating our version of
emscripten (a node dependency) would fix it, but this was
not the case.

Expunging the cache and redownloading the deps is unfortunate,
but it appears to work (has been removed in [1])

[1] https://skia-review.googlesource.com/c/skia/+/560917/3/infra/bots/gen_tasks_logic/gen_tasks_logic.go#b2100

Change-Id: Ib29c682433b1003a0d5aa9dbc0d374b42b33465b
Bug: skia:12541
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/561716
Reviewed-by: Joe Gregorio <jcgregorio@google.com>