[canvaskit] Temporarily disable some assertions in paragraph_client_icu
These are causing flaky test failures, but we cannot inspect the
visual output because we do not upload to Gold if the test fails.

To try to capture these, we are disabling them for now.

Example failure:
	Error: Expected 466.0997314453125 to be close to 558.349, 2.
	    at <Jasmine>
	    at skia/modules/canvaskit/tests/bazel/paragraph_test.js:1157:44
	    at skia/modules/canvaskit/tests/bazel/util.js:43:24
	Error: Expected 466.1000061035156 to be close to 758.349, 2.
	    at <Jasmine>
	    at skia/modules/canvaskit/tests/bazel/paragraph_test.js:1158:50
	    at skia/modules/canvaskit/tests/bazel/util.js:43:24
	Error: Expected 170.89999389648438 to be close to 341.399, 2.
	    at <Jasmine>
	    at skia/modules/canvaskit/tests/bazel/paragraph_test.js:1160:50
	    at skia/modules/canvaskit/tests/bazel/util.js:43:24

https://status.skia.org/errors/nJXdImxrBV54Am2QjzCn/0

Change-Id: Id9828b9eaba8e63501069e66133220f628a3aa7d
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/576839
Reviewed-by: Julia Lavrova <jlavrova@google.com>