Update patch set 3
Patch Set 3:

Thanks Eric!  Think I still have a problem though - I uploaded the most recent patch set with --bypass-hooks.

But when I try to upload regularly, I'm hitting some errors:

msarett-macbookair:skia msarett$ git cl upload
Using 50% similarity for rename/copy detection. Override with --similarity.
Running presubmit upload checks ...
Test failures:

==============================
rm 'infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/common.py'
rm 'infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/create.py'
rm 'infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/create_and_upload.py'
rm 'infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/download.py'
rm 'infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/upload.py'
Erm 'infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/VERSION'
rm 'infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/common.py'
rm 'infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/create.py'
rm 'infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/create_and_upload.py'
rm 'infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/download.py'
rm 'infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/upload.py'
Erm 'infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/VERSION'
rm 'infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/common.py'
rm 'infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/create.py'
rm 'infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/create_and_upload.py'
rm 'infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/download.py'
rm 'infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/upload.py'
E.....
======================================================================
ERROR: test_add_remove (assets.asset_utils_test.AssetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/skia/infra/bots/assets/asset_utils_test.py", line 183, in tearDown
    subprocess.check_call(['gsutil', 'ls', gs_path])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_upload_download (assets.asset_utils_test.AssetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/skia/infra/bots/assets/asset_utils_test.py", line 183, in tearDown
    subprocess.check_call(['gsutil', 'ls', gs_path])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_versions (assets.asset_utils_test.AssetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/skia/infra/bots/assets/asset_utils_test.py", line 183, in tearDown
    subprocess.check_call(['gsutil', 'ls', gs_path])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 8 tests in 0.423s

FAILED (errors=3)
Creating asset in /skia/infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2
Creating /skia/infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/download.py
Creating /skia/infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/upload.py
Creating /skia/infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/common.py
Creating /skia/infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/create.py
Creating /skia/infra/bots/assets/9bee8a91-dcd5-40c2-b688-e0d97ea863d2/create_and_upload.py
You will need to add implementation to the creation script.
Successfully created asset 9bee8a91-dcd5-40c2-b688-e0d97ea863d2.
Creating asset in /skia/infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad
Creating /skia/infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/download.py
Creating /skia/infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/upload.py
Creating /skia/infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/common.py
Creating /skia/infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/create.py
Creating /skia/infra/bots/assets/d0057548-faaa-459c-9cf4-54ce34c4dfad/create_and_upload.py
You will need to add implementation to the creation script.
Successfully created asset d0057548-faaa-459c-9cf4-54ce34c4dfad.
Creating asset in /skia/infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a
Creating /skia/infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/download.py
Creating /skia/infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/upload.py
Creating /skia/infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/common.py
Creating /skia/infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/create.py
Creating /skia/infra/bots/assets/170ed2a6-c395-401b-835d-440f8813cd5a/create_and_upload.py
You will need to add implementation to the creation script.
Successfully created asset 170ed2a6-c395-401b-835d-440f8813cd5a.

==============================

** Presubmit ERRORS **
`python infra/bots/infra_tests.py` failed:


Presubmit checks took 4.3s to calculate.

Patch-set: 3
Label: Code-Review=0