Update patch set 3
Patch Set 3: Code-Review+1

> Patch Set 3:
> 
> Did I do this right?

This looks like a fine way to do it to me.

> 
> Note-
> The change I uploaded using this: https://googleplex-android-review.git.corp.google.com/#/c/platform/external/skia/+/2877976/
> has presubmit failures: https://android-build.googleplex.com/builds/where-is-my-cl/googleplex-android-review/2877976?revision=1

If you dig into the logs (it's not obvious where to go here - "Build Logs" on the left, then "device_logcat_test.txt", then click the link for the "Full log"), you'll find this problem:

09-11 15:25:38.525  6682  6682 D skia    : frameworks/base/core/jni/android/graphics/Picture.cpp:123: fatal error: "assert(cullRect == myRect)"

An assert fired in the Android code. Android builds with SK_DEBUG defined are fairly rare, so it's no big surprise...

Looking at the assert, it was added in https://googleplex-android-review.git.corp.google.com/c/platform/frameworks/base/+/609112 (that is a merge from master-skia; I haven't found the original change). I don't think the assert is reasonable, though. In CreateFromStream we roundOut to get mWidth and mHeight, and here we expect it to be the same as the unrounded version.

I'll look into fixing this tomorrow (leaving office soon); without it, we might find we hit other asserts...

Patch-set: 3
Reviewer: Leon Scroggins <5255@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Label: Code-Review=+1