Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> out/soong/.intermediates/frameworks/base/libs/hwui/libhwui/android_arm_armv7-a-neon_core_static/obj/frameworks/base/libs/hwui/SkiaCanvasProxy.o frameworks/base/libs/hwui/SkiaCanvasProxy.cpp
> frameworks/base/libs/hwui/SkiaCanvasProxy.cpp:428:30: error: no member named 'kDefault_Positioning' in 'SkTextBlob'
>             case SkTextBlob::kDefault_Positioning:
>                  ~~~~~~~~~~~~^
> frameworks/base/libs/hwui/SkiaCanvasProxy.cpp:431:30: error: no member named 'kHorizontal_Positioning' in 'SkTextBlob'
>             case SkTextBlob::kHorizontal_Positioning: {
>                  ~~~~~~~~~~~~^
> frameworks/base/libs/hwui/SkiaCanvasProxy.cpp:439:30: error: no member named 'kFull_Positioning' in 'SkTextBlob'
>             case SkTextBlob::kFull_Positioning: {
>                  ~~~~~~~~~~~~^
> 3 errors generated.
> 
> 
> Grrr, Framework is using this private API, we'll need some sort of staging to update.

I don't think SkiaCanvasProxy is actively used anymore so we should be able to delete it.

Patch-set: 4