Reland "Move TraceHook into shared code."
This reverts commit 6ce91944f834729f1cf1ef876035e1c82be6285b.

Reason for revert: fixing Google3 issue

Original change's description:
> Revert "Move TraceHook into shared code."
>
> This reverts commit 7562d5eb70191bda3f52c14638086180bf350544.
>
> Reason for revert: Google3 test //third_party/skia/HEAD:skia_build_test
>  failing with error:
>
> In file included from third_party/skia/HEAD/src/core/SkOpts.cpp:49:
> third_party/skia/HEAD/src/opts/SkVM_opts.h:9:10: fatal error: 'src/sksl/tracing/SkSLTraceHook.h' file not found
> #include "src/sksl/tracing/SkSLTraceHook.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
>
> Original change's description:
> > Move TraceHook into shared code.
> >
> > This was previously SkVM-specific, but SkRP will also need to use
> > a trace hook to pass in trace data.
> >
> > (+Kevin for Bazel changes)
> >
> > Change-Id: I49324def6ba28c468db520ee2b81eef448819e51
> > Reviewed-on: https://skia-review.googlesource.com/c/skia/+/660383
> > Reviewed-by: Kevin Lubick <kjlubick@google.com>
> > Commit-Queue: John Stiles <johnstiles@google.com>
> > Auto-Submit: John Stiles <johnstiles@google.com>
> > Reviewed-by: Brian Osman <brianosman@google.com>
>
> Change-Id: Ibedadd6b79efe47400a90b1d2e7ef3d047a67e29
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/660796
> Auto-Submit: Arman Uguray <armansito@google.com>
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>

Change-Id: Iaee327777c43a03bd4f13781884b01de2f07fbd9
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/660856
Auto-Submit: John Stiles <johnstiles@google.com>
Reviewed-by: Kevin Lubick <kjlubick@google.com>