Fix Metal half-precision matrix negation.
Support for matrix negation in Metal was originally added at
http://review.skia.org/513976. Unfortunately this missed an edge
case--for half-precision matrix types, we need to use `-1.0h` instead
of `-1.0`. Otherwise, compilation will fail due to type mismatches:

Error Domain=MTLLibraryErrorDomain Code=3 "program_source:136:15: error: invalid operands to binary expression ('float' and 'metal::half2x2' (aka 'matrix<half, 2, 2>'))
    x = (-1.0 * x);
         ~~~~ ^ ~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.722/include/metal/metal_matrix:1870:34: note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'half')
METAL_FUNC matrix<T, Cols, Rows> operator*(T a, const thread matrix<T, Cols, Rows> &b)

(... many more rejected candidates are listed here)

Bug: skia:12627
Change-Id: I86a4b10f24cf8418de5b41457265f8ecf22e25d2
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/704943
Commit-Queue: John Stiles <johnstiles@google.com>
Commit-Queue: Brian Osman <brianosman@google.com>
Reviewed-by: Brian Osman <brianosman@google.com>
Auto-Submit: John Stiles <johnstiles@google.com>