Update patch set 4
Patch Set 4: Code-Review-1

I haven't had a chance to investigate, but this change breaks pathops
running pathops_unittest-V -x in debug on linux triggers

[101/106] PathOpsSimplifyRectsThreaded../../src/pathops/SkPathOpsCubic.cpp:256: fatal error: "assert(roughly_between(0, td/sd, 1) && roughly_between(0, te/se, 1))"

Patch-set: 4
Reviewer: Cary Clark <5632@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Label: Code-Review=-1