Update patch set 2
Patch Set 2:

Hmmm, failure on a couple of bots:

FAILED: /b/swarm_slave/w/irtnK9HZ/android_ndk_linux/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -MMD -MF obj/third_party/lua/src/lua.llex.o.d  -I../../../third_party/lua/src -w -fstrict-aliasing -fPIC -fvisibility=hidden -Werror -march=armv7-a -mfpu=neon -mthumb --sysroot=/b/swarm_slave/w/irtnK9HZ/android_ndk_linux/platforms/android-18/arch-arm --target=arm-linux-androideabi -B/b/swarm_slave/w/irtnK9HZ/android_ndk_linux/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin -Wno-unused-parameter -gline-tables-only -O1  -c ../../../third_party/lua/src/llex.c -o obj/third_party/lua/src/lua.llex.o
../../../third_party/lua/src/llex.c:214:18: error: no member named 'decimal_point' in 'struct lconv'
  ls->decpoint = getlocaledecpoint();
                 ^~~~~~~~~~~~~~~~~~~
../../../third_party/lua/src/llex.c:202:44: note: expanded from macro 'getlocaledecpoint'
#define getlocaledecpoint()     (localeconv()->decimal_point[0])
                                 ~~~~~~~~~~~~  ^
1 error generated.

Patch-set: 2
Reviewer: Mike Reed <5649@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Label: Commit-Queue=0