Add workaround for compiling with c++20 on Windows
Without this change, we see the following cryptic error
In file included from ../../../../../../skia/src/core/SkBitmapProcState_opts_ssse3.cpp:19:
In file included from ../../../../../../skia\src/opts/SkOpts_SetTarget.h:68:
In file included from C:\b\s\w\ir\clang_win\lib\clang\18\include\immintrin.h:603:
C:\b\s\w\ir\clang_win\lib\clang\18\include\rtmintrin.h(36,1): error: attribute 'target' multiversioning cannot be combined with attribute 'always_inline'
   36 | _xend(void)
      | ^
C:\b\s\w\ir\clang_win\lib\clang\18\include\intrin.h(167,6): note: function multiversioning caused by this declaration
  167 | void _xend(void);
      |      ^

This apparently [1] is because two incompatible headers are being
included that have inconsistent attributes. This has been fixed in
newer version of LLVM, but this should work around it on older
versions.

[1] https://github.com/llvm/llvm-project/issues/95133

Change-Id: I539c4d30941736d64ad1ae69e2d0ae2a6c2e155d
Bug: b/311238827
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/970996
Reviewed-by: Eric Boren <borenet@google.com>
Commit-Queue: Kaylee Lubick <kjlubick@google.com>