Reland "Revert "Add support for writing ICC profiles to webp encoder"
This reverts commit 3dbef9f184cfecadf14d4c424cf02ee2e8f68d44.

Reason for revert: Breaking Android roll. Error:

external/skia/src/images/SkWEBPImageEncoder.cpp:40:10: fatal error: 'webp/mux.h' file not found

It looks like we need to add that file to Android's copy of libwebp? (in external/webp)

Original change's description:
> Revert "Revert "Add support for writing ICC profiles to webp encoder""
> 
> This reverts commit e87d7781db75a7ec22a103eda0886c2ca8dc4d9d.
> 
> Reason for revert: Not the cause of the crashes.
> 
> Original change's description:
> > Revert "Add support for writing ICC profiles to webp encoder"
> > 
> > This reverts commit 0c9d0b4e03b6c10778329e995b5dfdcb97954b28.
> > 
> > Reason for revert: Looks like it's breaking a number of bots.
> > 
> > Original change's description:
> > > Add support for writing ICC profiles to webp encoder
> > > 
> > > Bug: skia:
> > > Change-Id: If0a8f84ed88da96924370b841f2283c0ff8e32ab
> > > Reviewed-on: https://skia-review.googlesource.com/10212
> > > Commit-Queue: Matt Sarett <msarett@google.com>
> > > Reviewed-by: Leon Scroggins <scroggo@google.com>
> > > 
> > 
> > TBR=msarett@google.com,scroggo@google.com,reviews@skia.org,jzern@google.com
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > 
> > Change-Id: Ic06ad9f19a4d743b34f8d3bd33f171b9d74badcb
> > Reviewed-on: https://skia-review.googlesource.com/11408
> > Reviewed-by: Jim Van Verth <jvanverth@google.com>
> > Commit-Queue: Jim Van Verth <jvanverth@google.com>
> > 
> 
> TBR=jvanverth@google.com,msarett@google.com,scroggo@google.com,reviews@skia.org,jzern@google.com
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> 
> Change-Id: I42f6ddefaf87c87b155640950b52a456952130ec
> Reviewed-on: https://skia-review.googlesource.com/11410
> Reviewed-by: Matt Sarett <msarett@google.com>
> Commit-Queue: Matt Sarett <msarett@google.com>
> 

TBR=jvanverth@google.com,msarett@google.com,scroggo@google.com,reviews@skia.org,jzern@google.com,mtklein@google.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Change-Id: I81f5b26bc641bf33b7a7d414ef55b15db9c323f6