Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> Looks like this fails the android roll: https://googleplex-android-review.git.corp.google.com/#/c/1813492/
> 
> out/target/product/angler/obj/NATIVE_TESTS/hwui_unit_tests_intermediates/tests/common/TestUtils.d -o out/target/product/angler/obj/NATIVE_TESTS/hwui_unit_tests_intermediates/tests/common/TestUtils.o frameworks/base/libs/hwui/tests/common/TestUtils.cpp"
> frameworks/base/libs/hwui/tests/common/TestUtils.cpp:198:13: error: 'getClipStack' is a private member of 'SkCanvas'
>     canvas->getClipStack()->getBounds(&clipBounds, &boundType);
>             ^
> external/skia/include/core/SkCanvas.h:1632:24: note: declared private here
>     const SkClipStack* getClipStack() const {
>                        ^
> 1 error generated.

This is only used by tests. Can they be updated to not rely on this? Or do we need to revert?

(I guess moving it to private is related to https://docs.google.com/document/d/1R8fhPlxH5fuv5u8zakRc4zdqeSG2xa04bEoG2gGEfws/edit#heading=h.dgq8lf3tmu1r ?)

Patch-set: 4