Update patch set 4
Patch Set 4:

Android bots failing with:

1 main.go:162] main.go:162 Error when compiling task with ID 5660449924186112: Could not prepare Skia checkout for compile: Error when running gn_to_bp: Failed to run gn_to_bp: Command exited with exit status 1: PATH=/mnt/pd0/checkouts/checkout_3/external/skia/bin/:/home/skia/bin:/home/skia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin python -c from gn import gn_to_bp; Stdout+Stderr:
ERROR at //gn/toolchain/BUILD.gn:33:58: Undefined identifier in string expansion.
  target_cc = "$ndk/toolchains/llvm/prebuilt/$_host/bin/$_target$ndk_api-clang"
                                                         ^------
"_target" is not currently in scope.
See //BUILD.gn:219:5: which caused the file to be included.
    source_set(target_name) {
    ^------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "gn/gn_to_bp.py", line 344, in <module>
    js = gn_to_bp_utils.GenerateJSONFromGN(gn_args)
  File "gn/gn_to_bp_utils.py", line 26, in GenerateJSONFromGN
    '--ide=json'])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gn', 'gen', '/tmp/tmpclKVKF', '--args=is_official_build=true skia_enable_fontmgr_android=false skia_enable_fontmgr_custom=false skia_enable_fontmgr_custom_empty=true skia_enable_fontmgr_win=false skia_enable_fontmgr_win_gdi=false skia_enable_tools=true skia_use_fixed_gamma_text=true skia_use_fontconfig=false skia_use_fonthost_mac=false skia_use_freetype=true skia_use_libheif=true skia_use_vulkan=true target_cpu="none" target_os="android"', '--ide=json']' returned non-zero exit status 1

Patch-set: 4
CC: Gerrit User 5145 <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>