Revert "Reconstruct subRun bounds from glyphs"
This reverts commit f93ed13d77fb28b1ab5c058c10bda3049ccbc5f5.

Reason for revert: SkRemoteGlyphCacheTest failures and build failures 

         ../../../../../skia/tests/SkRemoteGlyphCacheTest.cpp:193:37: error: unused function template 'get_container_ptr' [-Werror,-Wunused-template]
  193 | const sktext::gpu::SubRunContainer* get_container_ptr(const T& t) {
      |                                     ^~~~~~~~~~~~~~~~~
../../../../../skia/tests/SkRemoteGlyphCacheTest.cpp:212:37: error: unused function template 'get_container' [-Werror,-Wunused-template]
  212 | const sktext::gpu::SubRunContainer* get_container(T* slugImpl) {
      |                                     ^~~~~~~~~~~~~
2 errors generated.

and 

	
              ../../../../../skia/tests/SkRemoteGlyphCacheTest.cpp:660	Dst subrun is null for TransformedMaskSubRun [SkRemoteGlyphCache_SubRunBoundsReconstruction, OpenGL]

Original change's description:
> Reconstruct subRun bounds from glyphs
>
> * Reconstruct the bounds of a subRun after deserialization instead of packaging onto the VertexFiller.
>
> * An attacker could create a VertexFiller with creation bounds that did not contain its glyphs but were entirely contained within the current clip, enabling to the glyphs to ignore the creation bounds clip and sample from stale scratch textures
>
> Bug: b/513948227
> Change-Id: Ib4902657e6a50dd5675db4d73a1576b77c4ce88e
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1239916
> Commit-Queue: Thomas Smith <thomsmit@google.com>
> Reviewed-by: Michael Ludwig <michaelludwig@google.com>

Bug: b/513948227
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ide85466e17b870d2cc738bd25602d6cbf65d332b
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1249276
Auto-Submit: Michael Ludwig <michaelludwig@google.com>
Commit-Queue: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>