Revert "[rust png] Stop using and remove `SkXPS...PngHelpers.h` from Skia."
This reverts commit 6141aa6ccaf727c1ff9b8dfc948ac79ddff05561.

Reason for revert: chrome failures due to issues building pdfium

../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /c ../../third_party/pdfium/testing/pdfium_test.cc /Foobj/third_party/pdfium/tes...(too long)
../../third_party/pdfium/testing/pdfium_test.cc(87,10): fatal error: 'third_party/skia/include/docs/SkXPSLibpngHelpers.h' file not found
   87 | #include "third_party/skia/include/docs/SkXPSLibpngHelpers.h"  // nogncheck
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Original change's description:
> [rust png] Stop using and remove `SkXPS...PngHelpers.h` from Skia.
>
> This CL replaces usage of the helpers with a lambda provided by the
> callers (e.g. by `dm/DMSrcSink.cpp`).
>
> This CL also removes the helpers altogether, because Chromium and PDFium
> have already stopped using the helpers in
> https://pdfium-review.googlesource.com/137410 and
> https://crrev.com/c/7090470.
>
> This removal seems desirable based on the following:
>
> 1. No need for separate headers.
>    There is no need today for SVG- or XPS-specific encoding options.
>    If such a need arises in the future, then for backcompatibility we
>    would still need to keep the current helpers.  And since current
>    helpers are SVG- and XPS-agnostic, then it seems okay to just rely
>    directly on the API in `include/encode/...PngEncoder.h` headers.
> 2. No need for separate build components.
>    The separate build components (e.g. `skia_xps_libpng_public` in
>    `gn/xps.gni`, `xps_libpng_helpers` in `BUILD.gn`, `xps_libpng_hdrs`
>    in `include/docs/BUILD.bazel`) were tightly coupled with
>    the PNG encoder implementations.
> 3. Simplification.
>    After this CL there is less build components to manage:
>     - In theory `skia_xps_libpng_public` from `gn/xps.gni` would have to
>       be used in `skia/BUILD.gn` in Chromium and PDFium.
>     - In theory, in the future we would also have to have even more
>       components - e.g. `skia_svg_libpng_public` that would provide
>       dependency injection for `SkSVGCanvas::Make`.
> 4. Additional concerns (e.g. reducing the risk of breaking Skia clients
>    in the future) have been discussed in more detail during the code
>    review - see
>    https://skia-review.googlesource.com/c/skia/+/1082338/5#message-e592667c4a466ab0b2f52551f07760e9d2f9d960
>
> Bug: chromium:381900683
> Change-Id: If41f3f065fd38897ca61c5198924e3ab3af063ea
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1082338
> Reviewed-by: Kaylee Lubick <kjlubick@google.com>
> Reviewed-by: Ben Wagner <bungeman@google.com>
> Commit-Queue: Łukasz Anforowicz <lukasza@google.com>

Bug: chromium:381900683
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ia403f08b400d979c7a8fee4a3c2dde666b9ed213
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1087938
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Łukasz Anforowicz <lukasza@google.com>