Create patch set 2
Uploaded patch set 2.

Initial upload

Patch-set: 2
Patch-set-description: Initial upload
Subject: Revert "Android roll broke with a compilation error:"
Commit: 6638b7e3dbe1a855b6e65d971a2cfe524844667f
Hashtags: android-roll-broke-with-a-compilation-error
Tag: autogenerated:gerrit:newWipPatchSet
Groups: 6638b7e3dbe1a855b6e65d971a2cfe524844667f
Reviewer: Gerrit User 11059 <11059@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Label: Code-Review=+1
Work-in-progress: true
Attention: {"person_ident":"Gerrit User 5631 \u003c5631@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"REMOVE","reason":"Change was marked work in progress"}
Attention: {"person_ident":"Gerrit User 5656 \u003c5656@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"REMOVE","reason":"Change was marked work in progress"}
Attention: {"person_ident":"Gerrit User 5045 \u003c5045@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"REMOVE","reason":"Change was marked work in progress"}