Update patch set 9
Patch Set 9:

Android bot failed because of issue with git-on-borg:

Error when compiling task with ID 5727482686734336: Could not apply the patch with issue 196218 and patchset 9: Failed to fetch ref in /mnt/pd0/checkouts/checkout_9/external/skia: Command exited with exit status 128: git fetch http://skia.googlesource.com/a/skia.git refs/changes/18/196218/9; Stdout+Stderr:
error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502 Bad Gateway
fatal: The remote end hung up unexpectedly

Can you retry in a few minutes.

Patch-set: 9
CC: Gerrit User 5145 <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Work-in-progress: false