[bazel] Android build: Add missing Android-specific GPU dependency.
Today I noticed that some Android GPU tests no longer compile. Example:

$ bazel build //tests:ganesh_tests --config=for_android_arm64_with_rbe --config=gl_ganesh
...
ERROR: .../skia/tests/BUILD.bazel:156:18: Compiling tests/GrAHardwareBufferTest.cpp failed: (Exit 1): clang.sh failed: error executing command toolchain/android_trampolines/clang.sh -gcc-toolchain external/ndk_linux_amd64/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -fpic -isystem ... (remaining 147 arguments skipped)
tests/GrAHardwareBufferTest.cpp:15:10: fatal error: 'include/android/SkSurfaceAndroid.h' file not found
#include "include/android/SkSurfaceAndroid.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

This CL fixes the above and other compilation errors.

I tested this CL with the following Bazel builds (CPU-only tests are included in the list just to make sure I didn't inadvertently break non-GPU tests):

    $ bazel build //tests:ganesh_tests --config=for_android_arm64_with_rbe --config=gl_ganesh

    $ bazel build //tests:cpu_only_tests --config=for_android_arm64_with_rbe

Bug: skia:14227
Change-Id: I9e0b70f81f9ff30904782d1a77fa623625f977ea
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/697336
Reviewed-by: Kevin Lubick <kjlubick@google.com>
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>