Update patch set 14
Patch Set 14:

> Patch Set 14:
> 
> new android issues:
> 
> external/skia/modules/skparagraph/src/ParagraphStyle.cpp:4:10: fatal error: 'unicode/unistr.h' file not found
> #include "unicode/unistr.h"

That's expected and what https://skia-review.googlesource.com/c/skia/+/292718 aims to fix.

> 
> 
> external/skia/modules/skparagraph/src/OneLineShaper.cpp:549:33: error: no member named 'MakeShapeDontWrapOrReorder' in 'SkShaper'
>         auto shaper = SkShaper::MakeShapeDontWrapOrReorder();
>                       ~~~~~~~~~~^
> external/skia/modules/skparagraph/src/OneLineShaper.cpp:598:49: error: no member named 'MakeHbIcuScriptRunIterator' in 'SkShaper'
>                     auto scriptIter = SkShaper::MakeHbIcuScriptRunIterator
>                                       ~~~~~~~~~~^

Probably means SK_SHAPER_HARFBUZZ_AVAILABLE was false at build time. It is set if skia_enable_skshaper and skia_use_icu are set. I'm not sure if this is being passed along by the gn to bp script.

Patch-set: 14
Reviewer: Gerrit User 5140 <5140@5086850b-e599-37d2-8ec8-ff16aeccbf02>