Revert "Eval args of trace macros in debug builds"
This reverts commit ca0c82a968ddaf79c0705d6208ac45d9eda0692c.

Reason for revert:


../../src/sksl/SkSLCompiler.cpp:437:5: error: expected ';' after expression
    TRACE_EVENT0("skia.shaders", "SkSL::Compiler::convertProgram");
    ^
../../src/core/SkTraceEventCommon.h:75:29: note: expanded from macro 'TRACE_EVENT0'
#define TRACE_EVENT0(cg, n) TRACE_EMPTY(cg, n)
                            ^
../../src/core/SkTraceEventCommon.h:64:52: note: expanded from macro 'TRACE_EMPTY'
#define TRACE_EMPTY(...) do { sk_noop(__VA_ARGS__) } while (0)


Original change's description:
> Eval args of trace macros in debug builds
>
> Change-Id: I9ae48cfa23948fbdcdf6e8997365f5a8c2b3be8b
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/530677
> Reviewed-by: Brian Osman <brianosman@google.com>
> Commit-Queue: Brian Salomon <bsalomon@google.com>

Change-Id: Ia07d3c928c28d1f3409ba7b45970b2fd22f1a030
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/531097
Auto-Submit: John Stiles <johnstiles@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>