Update patch set 10
Patch Set 10:

> Patch Set 10:
> 
> I think this is really nice code. I looked pretty hard at any and the other register handling code. I saw nothing obvious. Can you tell if this is happening with the vector code ore the scalar code?

Vector I think.

I'm running out/fm -b cpu -s SkVM_cmp_f32 and getting this:
../tools/fm/fm.cpp:573: fatal error: "../tests/SkVMTest.cpp:633	out[1] == 0b001100
../tests/SkVMTest.cpp:634	out[2] == 0b001010
../tests/SkVMTest.cpp:635	out[3] == 0b001010
"

(And same when I simplify to_bit() in that test to  `return b.bit_and(mask, b.splat(1<<shift));`)

Since the errors are in the early lanes, I think it's a vector issue.  I've been tracking through the disassembly to see if anything is amiss, but haven't found anything yet.  I've been adding a `b.assert_true(m<m);` to the end of the program to get it to dump into the debugger.

Also been using some extra debug code when writing out the constants,

+                float f;
+                memcpy(&f, &imm, 4);
+                SkDebugf("splat %08x (%g), offset %d, kind %d, %d references\n",
+                         imm, f, label->offset, label->kind, label->references.count());
+                for (int off : label->references) {
+                    SkDebugf("\t%03x\n",off);
+                }

It all appears to be adding up.  :/

Patch-set: 10
Reviewer: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>