[bazel] Fix Android Vulkan build.
I tested this change as follows:

    $ bazel build //tests:known_good_android_ganesh_test \
        --config=for_android_arm64_with_rbe \
        --gpu_backend=vulkan_backend \
        --enable_gpu_test_utils

The deleted #include in GrAHardwareBufferImageGenerator.cpp appears unnecessary and causes the following error with --gpu_backend=vulkan_backend:

   src/gpu/ganesh/GrAHardwareBufferImageGenerator.cpp:36:10: fatal error: 'src/gpu/ganesh/gl/GrGLDefines_impl.h' file not found

The change in linkopts.bzl prevents the following error:

    ERROR: /usr/local/google/home/lovisolo/skia/tests/BUILD.bazel:666:18: configurable attribute "linkopts" in //tests:TextBlobCacheTest_native_test doesn't match this configuration. Would a default condition help?

Bug: skia:14227
Change-Id: I172eb70ee7d58a5ce49383efed72e460bee942df
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/694681
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: Kevin Lubick <kjlubick@google.com>