Update patch set 1
Patch Set 1:

Here are the breakages. It looks like this fx_skia_device.cpp file needs to include something  (SkColor.h? SkColorPriv.h?)

./../core/fxge/skia/fx_skia_device.cpp:366:28: error: use of undeclared identifier 'SkUnitScalarClampToByte'
      SkColorSetARGB(0xFF, SkUnitScalarClampToByte(pFunc->m_pBeginValues[0]),
                           ^
../../core/fxge/skia/fx_skia_device.cpp:367:22: error: use of undeclared identifier 'SkUnitScalarClampToByte'
                     SkUnitScalarClampToByte(pFunc->m_pBeginValues[1]),
                     ^
../../core/fxge/skia/fx_skia_device.cpp:368:22: error: use of undeclared identifier 'SkUnitScalarClampToByte'
                     SkUnitScalarClampToByte(pFunc->m_pBeginValues[2])));
                     ^
../../core/fxge/skia/fx_skia_device.cpp:370:28: error: use of undeclared identifier 'SkUnitScalarClampToByte'
      SkColorSetARGB(0xFF, SkUnitScalarClampToByte(pFunc->m_pEndValues[0]),
                           ^
../../core/fxge/skia/fx_skia_device.cpp:371:22: error: use of undeclared identifier 'SkUnitScalarClampToByte'
                     SkUnitScalarClampToByte(pFunc->m_pEndValues[1]),
                     ^
../../core/fxge/skia/fx_skia_device.cpp:372:22: error: use of undeclared identifier 'SkUnitScalarClampToByte'
                     SkUnitScalarClampToByte(pFunc->m_pEndValues[2])));
                     ^
../../core/fxge/skia/fx_skia_device.cpp:418:9: error: use of undeclared identifier 'SkPackARGB32'
        SkPackARGB32(0xFF, FloatToByte(floatColors[0]),
        ^

Patch-set: 1