table CF as runtime effect
This is not meant to be a serious suggestion to land, but I think
demonstrates a few sharp corners we might want to smooth:

  1) a color filter isn't allowed to sample its input with explicit
     coords, so the table data has to be in uniforms instead

  2) you can't index into uniforms with a non-constant index,
     so we need to loop over all possible indexes instead

  3) we don't allow looping this high, (int i = 0; i < 256; i++),
     so I've had to split it into two loops over low and high bits

  4) you can't actually write `int i = hi*16 + lo` then use `i`
     as the index, so I've written it out the long way every time

  5) this is too many uniforms for my laptop GPU,

  WARNING: Output of vertex shader 'vcolor_Stage0' not read by fragment
  shader ERROR: Implementation limit of 4096 (e.g., number of built-in
                plus user defined active uniforms components) exceeded,
                fragment shader uses 4100 total uniforms.
  ../src/gpu/GrShaderUtils.cpp:209:
  fatal error: "Shader compilation failed!"

No diffs in software, for what it's worth.

Change-Id: Ic0119ef33773c10eec25b593fa9db845eeae292b