Update patch set 4
Patch Set 4:

PS#4 should fix the Context leak, but I still need to figure out this build failure on Build-Ubuntu-Clang-x86_64-Release-Fast_NoBuildbot:

https://chromium-swarm.appspot.com/task?id=3403da0cdee8c210&refresh=10

../../../src/core/SkOpts.cpp -o obj/src/core/libskia.SkOpts.o
In file included from ../../../src/core/SkOpts.cpp:46:
../../../src/opts/SkRasterPipeline_opts.h:1093:11: error: no member named 'Load4' in '(anonymous namespace)::SkNx<8, float>'
    SkNf::Load4(buf, &r, &g, &b, &a);
    ~~~~~~^
1 error generated.

How can I trigger specific try bots other than the default set of git cl try with PolyGerrit?

Patch-set: 4