Revert "Reduce size of linear SkMaskGamma LUT"
This reverts commit 8cb8136c056ecdc7303d1a845bf5f33da9b32821.

Reason for revert: ../../../../../../skia/src/text/gpu/DistanceFieldAdjustTable.cpp:68: fatal error: "check(kExpectedDistanceAdjustTableSize == height)"


Original change's description:
> Reduce size of linear SkMaskGamma LUT
>
> Currently, SkMaskGamma uses C-style arrays for the LUT that are always
> allocated. These arrays aren't used at all for linear SkMaskGamma, and
> are quite large (roughly 2kb).
>
> This change updates the C-style 2D array into a flattend 1D array
> managed by a std::unique_ptr that gets reserved in the non-linear
> constructor.
>
> Before this change:
> 0:000> ?? sizeof(SkMaskGamma)
> unsigned int64 0x820 = 2080 bytes ~ 2kb
>
> After:
> 0:000> ?? sizeof(SkMaskGamma)
> unsigned int64 0x20 = 32 bytes
>
> Change-Id: Id1229eecafa13e9b738465a65da25e4019d493be
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/878336
> Reviewed-by: Ben Wagner <bungeman@google.com>
> Reviewed-by: Brian Osman <brianosman@google.com>
> Auto-Submit: Kurt Catti-Schmidt <kschmi@microsoft.com>
> Commit-Queue: Brian Osman <brianosman@google.com>

Change-Id: Ie964fe13df23bb65c258d5fc898c88346c344e3a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/889076
Auto-Submit: Michael Ludwig <michaelludwig@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>