[gn] Use the correct host toolchain in run_sksllex
- various targets in `BUILD.gn` point to `:run_sksllex` using the
  default toolchain; this action then depends on the executable
  built with the host toolchain
- when cross-compiling, while the `deps` is specified correctly,
  the path to the sksllex binary used by the python runner script
  always points to the default toolchain, instead of the host one
- fix by adding the toolchain subpath for sksllex binary for usage
  in run_sksllex.py

- testing, before:
```
\# the sksllex path points to the target one, which is arm64

rule ___run_sksllex___gn_toolchain_gcc_like__rule
  command = python3 ../../gn/run_sksllex.py /home/me/proj/skia/out/arm64/sksllex /home/me/proj/skia/bin/clang-format /home/me/proj/skia/bin/fetch-clang-format /home/me/proj/skia/src
  description = ACTION //:run_sksllex(//gn/toolchain:gcc_like)
  restat = 1

\# which then leads to the build to fail

me@me-mint22-base:~/proj/skia$ ninja -C out/arm64 :sksllex
me@me-mint22-base:~/proj/skia$ ninja -C out/arm64 ../../src/sksl/SkSLLexer.h
ninja: Entering directory `out/arm64'
[1/1] ACTION //:run_sksllex(//gn/toolchain:gcc_like)
FAILED: ../../src/sksl/SkSLLexer.h
python3 ../../gn/run_sksllex.py /home/me/proj/skia/out/arm64/sksllex /home/me/proj/skia/bin/clang-format /home/me/proj/skia/bin/fetch-clang-format /home/me/proj/skia/src
Traceback (most recent call last):
  File "/home/me/proj/skia/out/arm64/../../gn/run_sksllex.py", line 20, in <module>
    subprocess.check_output([sksllex, src + "/sksl/lex/sksl.lex", "Lexer",
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/me/proj/skia/out/arm64/sksllex'
```

- after (note: the path `/home/me/proj/skia/out/arm64/gcc_like_host/sksllex`):
```
\# now the sksllex binary is used from the gcc_like_host toolchain, which is x86_64 here

rule ___run_sksllex___gn_toolchain_gcc_like__rule
  command = python3 ../../gn/run_sksllex.py /home/me/proj/skia/out/arm64/gcc_like_host/sksllex /home/me/proj/skia/bin/clang-format /home/me/proj/skia/bin/fetch-clang-format /home/me/proj/skia/src
  description = ACTION //:run_sksllex(//gn/toolchain:gcc_like)
  restat = 1
```

Change-Id: I182235f59fde86bb4c5b3d7c26cc8f783c13ce7e
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/928177
Commit-Queue: Kaylee Lubick <kjlubick@google.com>
Reviewed-by: Kaylee Lubick <kjlubick@google.com>
Reviewed-by: Ravi Mistry <rmistry@google.com>