Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> This broke the flutter build:
> 
> https://chromium-swarm.appspot.com/task?id=3f7af74abd38cc10&refresh=10
> 
> 
> ../../flutter/lib/ui/painting/codec.cc:379:35: error: no member named 'kNone' in 'SkCodec'
>     if (requiredFrame != SkCodec::kNone) {

I uploaded https://skia-review.googlesource.com/c/skia/+/148663, which is in the CQ

Patch-set: 5