Update patch set 1
Patch Set 1:

> I was going to test this and find out, but for some reason I'm getting the following linking error:
>
> undefined reference to `wuffs_gif__decoder__frame_dirty_rect'

Try running "touch third_party/wuffs/wuffs.c" in order for the build system to pick up that that it has to re-build Wuffs itself (not just SkWuffsCodec), after you run tools/git-sync-deps.

I think that there is some mysterious interaction between gn, ninja, and the fact that Wuffs is delivered as a single file .h file instead of a traditional bunch of .c files, so that sometimes a manual intervention (touch) seems necessary. But it's been annoyingly difficult to repro reliably, and therefore difficult to figure out exactly what the problem is. Maybe adding the .h file to the third_party/wuffs/BUILD.gn file is the right approach, but it seems unusual, and without a repro, I'd just be guessing.

Patch-set: 1
Reviewer: Gerrit User 8223 <8223@5086850b-e599-37d2-8ec8-ff16aeccbf02>