Update patch set 20
Patch Set 20:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 134200: Change 134200 is work in progress

Patch-set: 20
Tag: autogenerated:cq:full-run