Revert "Check that instantiated texture matches the proxy's protectedness"
This reverts commit b3b8f3332cce37427ae62cd30fc3c1a3ce1a23bf.

Reason for revert: 
start unit test  VkProtectedContext_DrawRectangleWithFilter
../../../../../../skia/src/gpu/ganesh/GrSurfaceProxy.cpp:504: fatal error: "check(skgpu::Protected(surface->isProtected()) == this->isProtected())"

Original change's description:
> Check that instantiated texture matches the proxy's protectedness
>
>
> Change-Id: I9241c66f4312216dce8b0c1983dcfaf1c6ca8e50
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/738883
> Commit-Queue: Robert Phillips <robertphillips@google.com>
> Reviewed-by: Jim Van Verth <jvanverth@google.com>

Change-Id: Id84e792d422b9933553fd0546592f47c97cf5e30
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/745816
Auto-Submit: Robert Phillips <robertphillips@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>