Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Leon? any idea why the presubmit framework bot is failing?

Huh. Android is failing with the following errors [1]:

frameworks/base/libs/hwui/RecordingCanvas.h:138:7: error: abstract class is marked 'final' [-Werror,-Wabstract-final-class]
class RecordingCanvas final : public SkCanvasVirtualEnforcer<SkNoDrawCanvas> {
      ^
external/skia/include/core/SkCanvasVirtualEnforcer.h:67:10: note: unimplemented pure virtual method 'onDrawImageSet' in 'RecordingCanvas'
    void onDrawImageSet(const SkCanvas::ImageSetEntry[], int count, float alpha, SkFilterQuality,
         ^
In file included from frameworks/base/core/jni/android_view_ThreadedRenderer.cpp:55:
In file included from frameworks/base/libs/hwui/RenderNode.h:35:
frameworks/base/libs/hwui/RenderProperties.h:334:46: error: no member named 'setCameraLocation' in 'Sk3DView'
            mComputedFields.mTransformCamera.setCameraLocation(0, 0, distance);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
frameworks/base/libs/hwui/RenderProperties.h:342:74: error: no member named 'getCameraLocationZ' in 'Sk3DView'
        return const_cast<Sk3DView*>(&mComputedFields.mTransformCamera)->getCameraLocationZ();
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
3 errors generated.

These would all imply that SK_BUILD_FOR_ANDROID_FRAMEWORK is *not* defined. It's failing to build several files in frameworks/base with the same message. (And some more with other errors implying SK_BUILD_FOR_ANDROID_FRAMEWORK is not defined.)

I don't understand why that would be. Before each failure I see -Iexternal/skia/include/config/ and -Iexternal/skia/include/config/android. SkUserConfig.h (in include/config/android, which is set by the export_include_dirs) includes SkUserConfigManual.h (in include/config; also set by export_include_dirs), which defines SK_BUILD_FOR_ANDROID_FRAMEWORK. (I don't see any calls to undef it, either.) I'd expect all files in frameworks/base that depend on Skia files to include a Skia file, which would in turn include SkTypes.h -> SkUserConfig.h -> SkUserConfigManual.h -> #define SK_BUILD_FOR_ANDROID_FRAMEWORK.

I also do not reproduce the error locally. I even tried the commands that the bot is using:

lunch cf_x86_phone-eng
mmma -j50 frameworks/base/core/jni

and I successfully build. I'm syncing now, in case something has changed, but I'm baffled atm.

[1] https://storage.cloud.google.com/android-compile-logs/5702832225255424_withpatch_047012108

Patch-set: 3
Reviewer: Gerrit User 5255 <5255@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Label: Commit-Queue=0