Update patch set 3
Patch Set 3:

Looks like this causes some shader compile failures on Mac:

  ERROR: 0:14: 'textureRect' : no matching overloaded function found
  ERROR: 0:14: '=' : dimension mismatch
  ERROR: 0:14: 'assign' : cannot convert from 'const mediump float' to 'mediump 4-component vector of float'

Patch-set: 3
Reviewer: Gerrit User 5085 <5085@5086850b-e599-37d2-8ec8-ff16aeccbf02>