Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> CommandBuffer bot is past the failing bot_update.  Sigh.

And it looks like the Flutter failure is not infra-related:

In file included from ../../flutter/lib/ui/dart_ui.cc:13:
../../flutter/lib/ui/painting/gradient.h:20:1: error: static_assert failed "Need to update tile mode enum"
static_assert(SkShader::kTileModeCount == 3, "Need to update tile mode enum");
^             ~~~~~

Patch-set: 2
Reviewer: Eric Boren <5015@5086850b-e599-37d2-8ec8-ff16aeccbf02>