Revert "Delete more event tracing macros"
This reverts commit fd52317bf6d2acdbedf7477093204c9d642fcc22.

Reason for revert: 

../../flutter/shell/common/skia_event_tracer_impl.cc:34:12: error: use of undeclared identifier 'TRACE_EVENT_PHASE_BEGIN'
      case TRACE_EVENT_PHASE_BEGIN:

:(


Original change's description:
> Delete more event tracing macros
> 
> Also tried to clean up the comments to be clearer.
> 
> Bug: skia:
> Change-Id: I9762564a7f59bbfbd6a43afe902596d25ff1d523
> Reviewed-on: https://skia-review.googlesource.com/25364
> Reviewed-by: Mike Klein <mtklein@chromium.org>
> Commit-Queue: Brian Osman <brianosman@google.com>

TBR=mtklein@chromium.org,brianosman@google.com

Change-Id: I3869991b8aa3d0d67d12fbe76a207a1167801a63
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: skia: