Revert "Remove some flutter flags"
This reverts commit a58c14025a27e804c3471f5a4cef676d6f357f11.

Reason for revert: missed .mm call sites

../../flutter/shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm:163:17: error: no member named 'MakeScale' in 'SkMatrix'
      SkMatrix::MakeScale([UIScreen mainScreen].scale, [UIScreen mainScreen].scale);
      ~~~~~~~~~~^


Original change's description:
> Remove some flutter flags
>
> Change-Id: I45466d1134511d26a90a4874a0db709c6048dd8b
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/340760
> Reviewed-by: Mike Reed <reed@google.com>
> Commit-Queue: Mike Reed <reed@google.com>

TBR=reed@google.com

Change-Id: Ia9c21d1119c39d788a8c5272be1b0964527a5826
No-Presubmit: true
No-Tree-Checks: true
No-Try: true