Reland "[wgsl] Apply array polyfills in synthetic sksl tests correctly"
This reverts commit 0b10a4cf50a674678a49ae76c8365e7135988df2.

Reason for revert: remove assert

Original change's description:
> Revert "[wgsl] Apply array polyfills in synthetic sksl tests correctly"
>
> This reverts commit 0d60c01b23a6e43eea2652cf20a72c511a5b4174.
>
> Reason for revert: ../../../../../skia/src/sksl/codegen/SkSLWGSLCodeGenerator.cpp:1153: fatal error: "check(var.storage() == VariableStorage::kGlobal)"
>
>
> Original change's description:
> > [wgsl] Apply array polyfills in synthetic sksl tests correctly
> >
> > This refactors `writeUniformsAndBuffers`'s body that handled interface
> > blocks into a helper `writeInterfaceBlock` (logic unchanged) so that it
> > could be called by `writeNonBlockUniformsForTests` in place of it
> > generating bespoke WGSL that was 90% the same as the default generated
> > interface WGSL.
> >
> > This allows the synthetic global uniform block to participate in the
> > array polyfills and matrix polyfills correctly, although there was a
> > minor impact on generated test wgsl where @group and @binding changed
> > order.
> >
> > The array/matrix polyfill types also had to be updated to use @align(16)
> > instead of @size(16). The latter adjusts the size but does not propagate
> > the stricter alignment into any wrapping type.
> >
> > Bug: b/465408252
> > Change-Id: I41077f77ff8bd752f20c8e0f7603bfd4023a45cf
> > Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1121416
> > Commit-Queue: Michael Ludwig <michaelludwig@google.com>
> > Reviewed-by: Thomas Smith <thomsmit@google.com>
>
> Bug: b/465408252
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: Ie940e21f5391ffe87d92eb961e8a9ca932a5845b
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1143596
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Michael Ludwig <michaelludwig@google.com>

Bug: b/465408252
Change-Id: I32602e482b37311f412986bf5314381b17b0f5ad
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1143616
Auto-Submit: Michael Ludwig <michaelludwig@google.com>
Commit-Queue: Thomas Smith <thomsmit@google.com>
Reviewed-by: Thomas Smith <thomsmit@google.com>