Update patch set 20
Patch Set 20:

> Patch Set 20: Commit-Queue+1
> 
> > Skia Commit-Bot
> > Patch Set 19:
> >
> > RevisionConflictException: Error submitting change
> 
> From a chat with a team member:
> 
> Looks like the gerrit server is having some issues.  Possible work around- from the cli:
> git fetch origin master
> git pull
> #resolve potential merge conflict
> git cl upl -t rebase
> 
> <end of chat>
> 
> Nigel, I was able to upload a new (mostly unchanged) patch from my computer, but it changed the author to me. Do you want to try an upload from your computer to get the author fixed properly?

Oh yeah, it also gave me the message

Error 500: Internal server error

Endpoint: /changes/conflicts:*

So maybe it's still not fixed, even with my patch...

Patch-set: 20
Reviewer: Gerrit User 5255 <5255@5086850b-e599-37d2-8ec8-ff16aeccbf02>