Revert "Rewrite GrPathTessellateOp as GrPathInnerTriangulateOp"
This reverts commit ebb37e7db07d888dbdfcd541a3bd7352b3d8caec.

Reason for revert: fails Perf-Win2019-Clang-GCE-CPU-AVX2-x86_64-Release-All 

 Running tessellate_wangs_formula_cubic_log2_affine	nonrendering
 ../../../../../../skia/bench/TessellateBench.cpp(122): fatal error: "sum should be > 0."



Original change's description:
> Rewrite GrPathTessellateOp as GrPathInnerTriangulateOp
>
> Simplifies the op to always triangulate the inner fan. We ensure this
> will always work by using breadcrumb triangles. Also removes the
> fail-on-non-simple mode from GrInnerFanTriangulator since it isn't
> being used anymore.
>
> Bug: skia:10419
> Change-Id: Idb849712bf2bc4e5ef785bc3f9b8db03119d230e
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/359565
> Commit-Queue: Chris Dalton <csmartdalton@google.com>
> Reviewed-by: Brian Salomon <bsalomon@google.com>
> Reviewed-by: Jim Van Verth <jvanverth@google.com>

TBR=jvanverth@google.com,bsalomon@google.com,csmartdalton@google.com

Change-Id: Ic4455fa66bc60c8128c155d4dac7664ee0c3cd7c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: skia:10419