Revert "Use Chromium's abseil-cpp to unblock the Dawn roll"
This reverts commit 50e426ffb00a429fdccc35412ffafa8228f3fc30.

Reason for revert: Breaking Mac/Dawn bots

https://logs.chromium.org/logs/skia/6852658e4193ac11/+/steps/ninja/0/stdout

FAILED: obj/third_party/externals/abseil-cpp/absl/hash/internal/hash.hash.o 
/opt/s/w/ir/ccache_mac/bin/ccache clang++ -MD -MF obj/third_party/externals/abseil-cpp/absl/hash/internal/hash.hash.o.d -DNDEBUG -DSK_TRIVIAL_ABI=\[\[clang::trivial_abi\]\] -I../../../../../../skia/third_party/externals/abseil-cpp -Wno-attributes -ffp-contract=off -fstrict-aliasing -fPIC -fvisibility=hidden -isysroot /opt/s/w/ir/cache/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -target x86_64-apple-macos10.13 -O3 -g -gdwarf-4 -DREBUILD_IF_CHANGED_xcode_build_version=12c33 -Wno-gcc-compat -Wno-unreachable-code-break -std=c++17 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../skia/third_party/externals/abseil-cpp/absl/hash/internal/hash.cc -o obj/third_party/externals/abseil-cpp/absl/hash/internal/hash.hash.o
In file included from ../../../../../../skia/third_party/externals/abseil-cpp/absl/hash/internal/hash.cc:15:
../../../../../../skia/third_party/externals/abseil-cpp/absl/hash/internal/hash.h:602:53: error: 'path' is unavailable: introduced in macOS 10.15
              std::is_same_v<Path, std::filesystem::path>>>

Original change's description:
> Use Chromium's abseil-cpp to unblock the Dawn roll
>
> Dawn is now [1] using GN files from the Chromium Abseil repo.  Update
> to match.
>
> [1] https://dawn-review.googlesource.com/c/dawn/+/178940
>
> Change-Id: I45bc55f8f6e8d51bc83562a88eefbca8f67a51fe
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/825536
> Reviewed-by: Kevin Lubick <kjlubick@google.com>
> Commit-Queue: Florin Malita <fmalita@google.com>
> Reviewed-by: Robert Phillips <robertphillips@google.com>

Change-Id: Ie8fe379791cc6b3d1d0f9a1cd65167c652449617
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/825956
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Florin Malita <fmalita@google.com>