[canvaskit] compile_gm.sh: Ignore non-test C++ files in //gm directory.
This CL aims to fix Build-Debian10-EMCC-wasm-Release-WasmGMTests, which is currently failing with:

    wasm-ld: error: duplicate symbol: __original_main
    >>> defined in /tmp/emscripten_temp/BazelNoopRunner_4.o
    >>> defined in /tmp/emscripten_temp/BazelNoopRunner_435.o

    wasm-ld: error: duplicate symbol: main
    >>> defined in /tmp/emscripten_temp/BazelNoopRunner_4.o
    >>> defined in /tmp/emscripten_temp/BazelNoopRunner_435.o

    wasm-ld: error: duplicate symbol: __main_void
    >>> defined in /tmp/emscripten_temp/BazelNoopRunner_4.o
    >>> defined in /tmp/emscripten_temp/BazelNoopRunner_435.o

Bug: skia:14227
Change-Id: I5219cd5d010dcbefc74e1c8b587da74ab0b92ce2
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/720058
Auto-Submit: Leandro Lovisolo <lovisolo@google.com>
Commit-Queue: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: James Godfrey-Kittle <jamesgk@google.com>
Commit-Queue: James Godfrey-Kittle <jamesgk@google.com>