Revert "Add synonyms to GLSLGeneration for 100es and 300es."
This reverts commit 63e7ba59ce32a8612be23ea0992b93b8dd360ec3.

Reason for revert: Angle errors

Errors:
ERROR: 0:62: 'ldexp' : no matching overloaded function found
ERROR: 0:65: 'ldexp' : no matching overloaded function found

https://logs.chromium.org/logs/skia/5911c43abda19c11/+/steps/nanobench/0/stdout

Original change's description:
> Add synonyms to GLSLGeneration for 100es and 300es.
>
> We use GLSLGeneration::k330 to mean GLSL 3.30 for desktop GLSL and also
> for ES 3.00. k110 lived a double life as ES 1.00. This was confusing, so
> several places in the code had comments like "this is the value for GLSL
> ES 3" to clarify.
>
> This CL adds new enums "k100es" and "k300es" which use the same values
> as "k110" and "k330", but make the code easier to understand at a
> glance.
>
> Change-Id: Ib4dfbd8cd7bab45b35d6ad7303ccf87c7eeca3ab
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/506898
> Auto-Submit: John Stiles <johnstiles@google.com>
> Commit-Queue: John Stiles <johnstiles@google.com>
> Reviewed-by: Greg Daniel <egdaniel@google.com>
> Commit-Queue: Greg Daniel <egdaniel@google.com>

Change-Id: I7703598d4c74361da588d23f64e0697a844429ad
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/508517
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Florin Malita <fmalita@google.com>
Commit-Queue: Florin Malita <fmalita@google.com>