Fix Flutter BuildStats job
This vpython3 folder does not yet exist. Perhaps the failures we
are observing

Traceback (most recent call last):
  File "flutter/tools/gn", line 10, in <module>
    import argparse
ModuleNotFoundError: No module named 'argparse'

Are due to a stale vpython cache.

Change-Id: I4818dbccc0f8d00d2198b8557d39057fe8472200
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/563117
Reviewed-by: Florin Malita <fmalita@google.com>