Revert "Roll skia/third_party/externals/angle2/ a60d35672..09cd47779 (3 commits)"
This reverts commit 30185bf5c54148ed4b8d609049f3ed3cf17c423c.

Reason for revert: Failing on Build-Debian9-GCC-x86_64-Release-ANGLE [1]

../../../third_party/externals/angle2/src/libANGLE/Framebuffer.cpp:201:36: error: comparison between ‘enum gl::<anonymous>’ and ‘enum gl::Framebuffer::DirtyBitType’ [-Werror=enum-compare]
                   gl::Framebuffer::DIRTY_BIT_COLOR_ATTACHMENT_MAX,
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../third_party/externals/angle2/src/libANGLE/Framebuffer.cpp:204:36: error: comparison between ‘enum gl::<anonymous>’ and ‘enum gl::Framebuffer::DirtyBitType’ [-Werror=enum-compare]
                   gl::Framebuffer::DIRTY_BIT_DEPTH_ATTACHMENT,
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

It appears that [2] changed this line.
[1] https://chromium-swarm.appspot.com/task?id=38fc09e8e73db910&refresh=10#
[2] https://chromium.googlesource.com/angle/angle.git/+/05b35b210ef3dcdf7e3260d192ce51b602b6f3a7%5E%21/#F2

Original change's description:
> Roll skia/third_party/externals/angle2/ a60d35672..09cd47779 (3 commits)
> 
> https://chromium.googlesource.com/angle/angle.git/+log/a60d35672ed9..09cd47779d21
> 
> $ git log a60d35672..09cd47779 --date=short --no-merges --format='%ad %ae %s'
> 2017-09-27 geofflang Remove references to the framebuffer fetch extensions in the GL layer.
> 2017-09-26 geofflang Make query extensions enableable.
> 2017-10-03 jmadill D3D11: Lazy robust resource init.
> 
> Created with:
>   roll-dep skia/third_party/externals/angle2
> 
> 
> Documentation for the AutoRoller is here:
> https://skia.googlesource.com/buildbot/+/master/autoroll/README.md
> 
> If the roll is causing failures, see:
> http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium#TOC-Failures-due-to-DEPS-rolls
> 
> 
> CQ_INCLUDE_TRYBOTS=skia.primary:Perf-Win10-MSVC-AlphaR2-GPU-RadeonR9M470X-x86_64-Debug-ANGLE,Perf-Win10-MSVC-Golo-GPU-QuadroP400-x86_64-Debug-ANGLE,Perf-Win10-MSVC-NUC5i7RYH-GPU-IntelIris6100-x86_64-Debug-ANGLE,Perf-Win10-MSVC-NUC6i5SYK-GPU-IntelIris540-x86_64-Debug-ANGLE,Perf-Win10-MSVC-NUCD34010WYKH-GPU-IntelHD4400-x86_64-Debug-ANGLE,Perf-Win10-MSVC-ShuttleC-GPU-GTX960-x86_64-Debug-ANGLE,Test-Win10-MSVC-AlphaR2-GPU-RadeonR9M470X-x86_64-Debug-ANGLE,Test-Win10-MSVC-Golo-GPU-QuadroP400-x86_64-Debug-ANGLE,Test-Win10-MSVC-NUC5i7RYH-GPU-IntelIris6100-x86_64-Debug-ANGLE,Test-Win10-MSVC-NUC6i5SYK-GPU-IntelIris540-x86_64-Debug-ANGLE,Test-Win10-MSVC-NUCD34010WYKH-GPU-IntelHD4400-x86_64-Debug-ANGLE,Test-Win10-MSVC-ShuttleC-GPU-GTX960-x86_64-Debug-ANGLE
> TBR=scroggo@google.com
> 
> Change-Id: I7966c43a7e5b33a4b82097c6a136e7368c7b8f0b
> Reviewed-on: https://skia-review.googlesource.com/54440
> Reviewed-by: angle-deps-roller . <angle-deps-roller@chromium.org>
> Commit-Queue: angle-deps-roller . <angle-deps-roller@chromium.org>

TBR=scroggo@google.com,angle-deps-roller@chromium.org

Change-Id: I7a18fa4b8a87c9e8389e64b942fa93af7cef0917
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Cq-Include-Trybots: skia.primary:Perf-Win10-MSVC-AlphaR2-GPU-RadeonR9M470X-x86_64-Debug-ANGLE, Perf-Win10-MSVC-Golo-GPU-QuadroP400-x86_64-Debug-ANGLE, Perf-Win10-MSVC-NUC5i7RYH-GPU-IntelIris6100-x86_64-Debug-ANGLE, Perf-Win10-MSVC-NUC6i5SYK-GPU-IntelIris540-x86_64-Debug-ANGLE, Perf-Win10-MSVC-NUCD34010WYKH-GPU-IntelHD4400-x86_64-Debug-ANGLE, Perf-Win10-MSVC-ShuttleC-GPU-GTX960-x86_64-Debug-ANGLE, Test-Win10-MSVC-AlphaR2-GPU-RadeonR9M470X-x86_64-Debug-ANGLE, Test-Win10-MSVC-Golo-GPU-QuadroP400-x86_64-Debug-ANGLE, Test-Win10-MSVC-NUC5i7RYH-GPU-IntelIris6100-x86_64-Debug-ANGLE, Test-Win10-MSVC-NUC6i5SYK-GPU-IntelIris540-x86_64-Debug-ANGLE, Test-Win10-MSVC-NUCD34010WYKH-GPU-IntelHD4400-x86_64-Debug-ANGLE, Test-Win10-MSVC-ShuttleC-GPU-GTX960-x86_64-Debug-ANGLE