Revert "Replace fatal logging with SK_ABORT macro"
This reverts commit 4453a8598b653b5a45e222b09d12023c2dba6b23.

Reason for revert: breaking chrome roll

../../skia/ext/google_logging.cc:21:25: error: no member named 'kFatal' in 'SkLogPriority'
   21 |     case SkLogPriority::kFatal:
      |                         ^~~~~~

Original change's description:
> Replace fatal logging with SK_ABORT macro
>
> Updates SK_ABORT macro to use SkLog macro instead of SkDebugf, and updates call sites to not add an extra newline.
>
> Change-Id: I5ccff6d8e0143a6d352f7f56e6a192a0e5b33ef0
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1240978
> Reviewed-by: Noelle Scobie <nscobie@google.com>
> Commit-Queue: Jorge Betancourt <jmbetancourt@google.com>

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ia17ec333dd520e57a91d4ef18ce5b192064d0d22
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/1246376
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Florin Malita <fmalita@google.com>