Update patch set 2
Patch Set 2:

Hate to say it... I think this one also breaks the Android roll until that SkGaussianEdgeShader CL gets into master.

In file included from frameworks/base/libs/hwui/pipeline/skia/ReorderBarrierDrawables.cpp:24:
external/skia/src/effects/SkGaussianEdgeShader.h:11:10: fatal error: 'SkShaderBase.h' file not found
#include "SkShaderBase.h"

Patch-set: 2
CC: Mike Klein <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>