Update patch set 1
Patch Set 1:

Need to disable warnings in ANGLE, and think about what to do about a smarter UBSAN,

FAILED: obj/third_party/externals/angle2/src/libANGLE/renderer/d3d/d3d11/libGLESv2.formatutils11.obj 
"c:\b\s\w\ir\clang_win/bin/clang-cl.exe" /nologo /showIncludes /FC -DLIBANGLE_IMPLEMENTATION -DLIBGLESV2_IMPLEMENTATION -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_ENABLE_OPENGL -DEGL_EGLEXT_PROTOTYPES -DGL_GLEXT_PROTOTYPES -DANGLE_ENABLE_D3D11 -DANGLE_ENABLE_D3D9 -DGL_APICALL= -DGL_API= -DEGLAPI= -Igen/angle2 -I../../../../../../skia/third_party/externals/angle2/include -I../../../../../../skia/third_party/externals/angle2/src -I../../../../../../skia/third_party/externals/angle2/src/common/third_party/base -I../../../../../../skia/third_party/externals/angle2/src/third_party/khronos /WX /bigobj /utf-8 -fms-compatibility-version=19 -imsvc c:\b\s\w\ir\win_toolchain/VC/Tools/MSVC/14.16.27023/include -imsvc c:\b\s\w\ir\win_toolchain/win_sdk/Include/10.0.17763.0/shared -imsvc c:\b\s\w\ir\win_toolchain/win_sdk/Include/10.0.17763.0/ucrt -imsvc c:\b\s\w\ir\win_toolchain/win_sdk/Include/10.0.17763.0/um -imsvc c:\b\s\w\ir\win_toolchain/win_sdk/Include/10.0.17763.0/winrt /O2 /Zc:inline /Z7 -gcodeview-ghash -Wno-unused-parameter -DDUMMY_clang_win_version=14  /std:c++17 /GR- /wd4577 -Wno-tautological-constant-compare -Wno-nonportable-include-path /c ../../../../../../skia/third_party/externals/angle2/src/libANGLE/renderer/d3d/d3d11/formatutils11.cpp /Foobj/third_party/externals/angle2/src/libANGLE/renderer/d3d/d3d11/libGLESv2.formatutils11.obj /Fd"obj/third_party/angle2/libGLESv2_c.pdb"
In file included from ../../../../../../skia/third_party/externals/angle2/src/libANGLE/renderer/d3d/d3d11/formatutils11.cpp:10:
In file included from ../../../../../../skia/third_party/externals/angle2/src\libANGLE/renderer/d3d/d3d11/formatutils11.h:18:
In file included from ../../../../../../skia/third_party/externals/angle2/src\libANGLE/renderer/copyvertex.h:67:
../../../../../../skia/third_party/externals/angle2/src\libANGLE/renderer/copyvertex.inc.h(196,76): error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
                    offsetOutput[j] = static_cast<float>(offsetInput[j]) / NL::max();
                                                                         ~ ^~~~~~~~~
../../../../../../skia/third_party/externals/angle2/src/libANGLE/renderer/d3d/d3d11/formatutils11.cpp(655,49): note: in instantiation of function template specialization 'rx::CopyTo32FVertexData<int, 1, 1, true>' requested here
                                               &CopyTo32FVertexData<GLint, 1, 1, true>);


and 

 ../../../../../../skia/third_party/externals/libjpeg-turbo/jdsample.c:99:49: runtime error: applying zero offset to null pointer

Patch-set: 1
Reviewer: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>