Fix VkDeps roller.
The VkDeps roller is currently stuck[1]. The reason is that the following tasks are failing to compile after rolling vulkan-deps (and its transitive deps):

- BazelBuild-example_hello_world_dawn-release-linux_x64
- BazelBuild-skia_public-enforce_iwyu-linux_x64

In both cases, the compile error is as follows:

    external/dawn/src/tint/reader/spirv/enum_converter.h:18:10: fatal error: 'spirv/unified1/spirv.h' file not found
    #include "spirv/unified1/spirv.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~

This CL fixes the above error by adding @spirv_headers//:spirv_c_header as a dependency of //bazel/external/dawn:tint, which provides the missing header file.

I tested this change by locally patching the failing CL[1] and ensuring that the following Bazel invocations succeed:

  $ bazelisk build //example:hello_world_dawn --config=release --config=for_linux_x64_with_rbe --jobs=100 --remote_download_minimal --nobuild_runfile_manifests --nobuild_runfile_links

  $ bazelisk build //:skia_public --config=enforce_iwyu --config=for_linux_x64_with_rbe --jobs=100 --remote_download_minimal --nobuild_runfile_manifests --nobuild_runfile_links

[1] https://skia-review.googlesource.com/c/skia/+/603290

Change-Id: I50811af7042fa0f0245ac07d9ad0acb07a8fe97c
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/603424
Auto-Submit: Leandro Lovisolo <lovisolo@google.com>
Reviewed-by: Kevin Lubick <kjlubick@google.com>
Commit-Queue: Kevin Lubick <kjlubick@google.com>