Revert "Revert "8-bit jumper on armv8""
This reverts commit 6d13575108299951ecdfba6d85c915fcec2bc028.

Now with guards for "errors" like this:
    external/skia/src/jumper/SkJumper_stages_8bit.cpp:240:50: error:
    'memcpy' called with size bigger than buffer
                case 12: memcpy(&v, src, 12*sizeof(T)); break;

This code is unreachable and generally removed by Clang's optimizer
anyway...

Change-Id: I6216567caaa6166f71258bd25343a09e93892a10