Revert "[graphite] Reenable tiled image cache size heuristic"
This reverts commit 2f82ef6e77774dc4e8e382b2fb6159c58c0f8725.

Reason for revert: This change is breaking the Chrome roller. "src/gpu/graphite/TiledTextureUtils_Graphite.cpp:155:33: error: no member named 'resourceCache' in 'skgpu::graphite::RecorderPriv'
return recorder->priv().resourceCache()->getMaxBudget();" - it looks like we are trying to use the resourceCache() method which is only defined when GRAPHITE_TEST_UTILS are enabled. Reverting since original issuer is OOO today.

Original change's description:
> [graphite] Reenable tiled image cache size heuristic
>
> I'm not sure how often this heuristic actually triggers but this increases the parallelism between the Graphite and Ganesh implementations.
>
> Bug: b/267656937
> Change-Id: I657d8a180759c1fd94d3482dba197408b4fc5b0f
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/718556
> Reviewed-by: Jim Van Verth <jvanverth@google.com>
> Commit-Queue: Robert Phillips <robertphillips@google.com>

Bug: b/267656937
Change-Id: I7a2f6a33d5c27f0346c14d7b113748c1bbd9753e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/718979
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Nicolette Prevost <nicolettep@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>