Update patch set 6
Patch Set 6:

> Patch Set 5:
> 
> > Patch Set 5:
> > 
> > Now that my nullable FP change has landed (and hopefully won't be reverted this time...) you should be able to remove the null effect. You can make fragment processors nullable in SkSL by declaring them as type "fragmentProcessor?", and then check to see whether they were actually provided by comparing them against null within the .fp file.
> 
> Thanks Ethan!

I'm running into an issue at runtime:

 164			half4 in0 = _child0;
 165			if (false) 
 166			{
 167				output_Stage2 = mix(in0, _child1, uweight_Stage2);
 168			}
 169			else 
 170			{
 171				output_Stage2 = mix(in0, output_Stage1, uweight_Stage2);
 172			}

Errors:
error: 167: unknown identifier '_child1'
1 error

Am I missing some trick to prune dead branches at pre-processing time?  I guess we could also emit dummy declarations for null FPs?

Patch-set: 6
Reviewer: Gerrit User 5641 <5641@5086850b-e599-37d2-8ec8-ff16aeccbf02>