Add SK_BUILD_NO_OPTS to mac base defines
It looked like the mac build worked without this, but it turns out much
further down the pipeline I end up getting:

Undefined symbols for architecture x86_64:
  "SkOpts::Init_sse42()", referenced from:
      SkOpts::init() in libskia.a(SkOpts_cc0e566366dcb82e419fc25db4f55650.o)
  "SkOpts::Init_avx()", referenced from:
      SkOpts::init() in libskia.a(SkOpts_cc0e566366dcb82e419fc25db4f55650.o)
  "SkOpts::Init_hsw()", referenced from:
      SkOpts::init() in libskia.a(SkOpts_cc0e566366dcb82e419fc25db4f55650.o)
  "SkOpts::Init_skx()", referenced from:
      SkOpts::init() in libskia.a(SkOpts_cc0e566366dcb82e419fc25db4f55650.o)
ld: symbol(s) not found for architecture x86_64

Adding this flag back gets rid of the linker errors which makes sense.

Change-Id: I4b9a2d80daa0f373e64a430c4fb770a9c25c5e80
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/300224
Reviewed-by: Mike Klein <mtklein@google.com>
Commit-Queue: Mike Klein <mtklein@google.com>