Update patch set 5
Patch Set 5:

Looks like this broke Test-Win10-Clang-Golo-GPU-QuadroP400-x86_64-Debug-All-BonusConfigs
 and Test-Win10-Clang-Golo-GPU-QuadroP400-x86_64-Release-All-BonusConfigs.

https://chromium-swarm.appspot.com/task?id=47a238dc63e68010

Snippet:

start glbetex svg  android.svg
../../../../../../skia/src/gpu/GrRenderTargetContext.cpp(214): fatal error: "assert(fOpsTask)"


Caught exception 2147483651 EXCEPTION_BREAKPOINT	glbetex svg  android.svg
Caught exception 2147483651 EXCEPTION_BREAKPOINT, was running:
	glbetex svg  android.svg
	glbetex svg  android.svg
Likely culprit:
	glbetex svg  android.svg
c:\b\s\w\ir\build\dm exited with status -2147483645

Patch-set: 5
CC: Gerrit User 5145 <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>