Revert "factor out SkCTFontCreateExactCopy into its own file(s)"
This reverts commit f96a0703397ff486a97b0783b581c41dea4ecd83.

Reason for revert: blocking G3 roll with:

third_party/skia/HEAD/src/ports/SkScalerContext_mac_ct.cpp:50:10: fatal error: 'third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.h' file not found
   50 | #include "third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

third_party/skia/HEAD/src/ports/SkTypeface_mac_ct.cpp:60:10: fatal error: 'third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.h' file not found
   60 | #include "third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.cpp:18:10: fatal error: 'third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.h' file not found
   18 | #include "third_party/skia/HEAD/src/utils/mac/SkCTFontCreateExactCopy.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original change's description:
> factor out SkCTFontCreateExactCopy into its own file(s)
>
> This function attempts to resize a CTFont without inadvertently changing unrelated properties, like the optical size, relative glyph metrics, or the underlying font data used.
>
> Placing it in a separate file allows other clients to change its behavior without needing to have a 'patch' on the skia sources -- they can just replace this file with their alternative.
>
> Change-Id: If1330690b6a1b6afdfca7601aa8b7f9888c1ff6f
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/822557
> Commit-Queue: Mike Reed <mike@reedtribe.org>
> Reviewed-by: Florin Malita <fmalita@google.com>
> Reviewed-by: Ben Wagner <bungeman@google.com>

Change-Id: Ib42e0b29f8f18284ce1b94ccf8243c80eddc1cde
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/823576
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Robert Phillips <robertphillips@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>