Revert "FPS and frame control for MSKP slide."
This reverts commit 3b7587814de8f4b3c4970603ac4cd8565adb433c.

Reason for revert: Failing on Housekeeper-PerCommit-CreateDockerImage_Skia_Release:

obj/tools/viewer/viewer.MSKPSlide.o
../../tools/viewer/MSKPSlide.cpp:64:23: error: no member named 'clamp' in namespace 'std'

        fFrame = std::clamp(fFrame, 0, fPlayer->numFrames() - 1);


Original change's description:
> FPS and frame control for MSKP slide.
>
> Bug: skia:11900
> Change-Id: Ib4d8da6a86da7966e613de2d7cfd61ff545b296a
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/400676
> Commit-Queue: Brian Salomon <bsalomon@google.com>
> Reviewed-by: Jim Van Verth <jvanverth@google.com>

TBR=jvanverth@google.com,bsalomon@google.com

Change-Id: I4a97deb1ac441f223977d2dbad2f93f5d4376a23
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: skia:11900
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/402777
Reviewed-by: Joe Gregorio <jcgregorio@google.com>