Revert "[graphite] Test that failed dst copies don't cause a crash"
This reverts commit 64980a5a3adc80f1379d54f1570491e92e244fa2.

Reason for revert: This fails to compile with
skia_enable_vello_shaders=true, giving the following error:

  In file included from ../../../tests/graphite/DrawPassTest.cpp:14:
  In file included from ../../../src/gpu/graphite/RendererProvider.h:16:
  In file included from ../../../src/gpu/graphite/compute/VelloRenderer.h:15:
  In file included from ../../../src/gpu/graphite/compute/VelloComputeSteps.h:15:
  ../../../third_party/vello/cpp/vello.h:9:10: fatal error: 'third_party/vello/src/lib.rs.h' file not found
  #include "third_party/vello/src/lib.rs.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

This is strange to me because other Graphite source files that include
RendererProvider.h compile fine with Vello.

Original change's description:
> [graphite] Test that failed dst copies don't cause a crash
>
> This adds a test which would segfault if not for review.skia.org/755577
> and review.skia.org/764417.
>
> Bug: chromium:1489392
> Change-Id: Iaa83005f0a46522e754de536a86ed912a6e84061
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/766600
> Reviewed-by: Greg Daniel <egdaniel@google.com>
> Commit-Queue: James Godfrey-Kittle <jamesgk@google.com>

Bug: chromium:1489392
Change-Id: Ic4a6b6a67d15b25d805be5c17fbde946e7186709
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/767416
Reviewed-by: James Godfrey-Kittle <jamesgk@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: James Godfrey-Kittle <jamesgk@google.com>