Update patch set 1
Patch Set 1:

Fixing:

Traceback (most recent call last):
  File "/mnt/data/home/mali/src/chromium/src/third_party/skia/gn/is_clang.py", line 14, in <module>
    if ('clang' in subprocess.check_output('%s --version' % cc, shell=True) and
TypeError: a bytes-like object is required, not 'str'

Patch-set: 1
Reviewer: Gerrit User 5045 <5045@5086850b-e599-37d2-8ec8-ff16aeccbf02>
Work-in-progress: false
Attention: {"person_ident":"Gerrit User 5641 \u003c5641@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Change was marked ready for review"}
Attention: {"person_ident":"Gerrit User 5045 \u003c5045@5086850b-e599-37d2-8ec8-ff16aeccbf02\u003e","operation":"ADD","reason":"Reviewer was added"}