Add SK_NO_SANITIZE_CFI that has effect when building with Clang
Introduce a new SK_NO_SANITIZE_CFI macro, which expands to
SK_NO_SANITIZE("cfi") with Clang, or to nothing otherwise.

Clang supports CFI sanitization, and therefore the no_sanitize("cfi")
function attribute works there as intended; but other compilers that
do not support the feature may warn about the sanitizer name being
unrecognized.

For example, WebKit makes developer builds use -Werror, resulting in the
following error when building with GCC:

    In file included from /app/webkit/WebKitBuild/GTK/Release/Skia/Headers/top/skia/core/SkCanvas.h:35,
		     from /app/webkit/Source/WebKit/WebProcess/WebPage/gtk/WebPrintOperationGtk.h:40,
		     from /app/webkit/Source/WebKit/WebProcess/WebPage/WebPage.h:84,
		     from /app/webkit/Source/WebKit/NetworkProcess/Authentication/AuthenticationManager.cpp:38,
		     from /app/webkit/WebKitBuild/GTK/Release/DerivedSources/WebKit/unified-sources/UnifiedSource-72468c22-4.cpp:2:
    /app/webkit/Source/ThirdParty/skia/include/private/base/SkTArray.h:621:33: error: ‘cfi’ attribute directive ignored [-Werror=attributes]
      621 |     static T* TCast(void* buffer) {
	  |                                 ^
    cc1plus: all warnings being treated as errors

This fix allows building with warnings-as-errors when using GCC.

Change-Id: I5f13589535f479a545cad104b4bca065d7a36e42
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/930996
Reviewed-by: Ben Wagner <bungeman@google.com>
Auto-Submit: Adrian Perez de Castro <aperez@igalia.com>
Commit-Queue: Ben Wagner <bungeman@google.com>
Reviewed-by: Michael Ludwig <michaelludwig@google.com>