Revert "Limit stack calling depth from GrTriangulator::mergeCollinearEdges()."
This reverts commit a38c4ae0287a1d6d4a57db85b8b52c0d43965deb.

Reason for revert: 

	start glesmsaa4 gm  labyrinth_round
../../../../../../skia/src/gpu/ganesh/geometry/GrTriangulator.cpp:1419: fatal error: "check(left->isLeftOf(*right->fBottom))"

Caught signal 4 [Illegal instruction] (297MB RAM, peak 495MB), was running:

Caught signal 4 [Illegal instruction] (297MB RAM, peak 495MB), was running:
	glesmsaa4 gm  labyrinth_round

Original change's description:
> Limit stack calling depth from GrTriangulator::mergeCollinearEdges().
>
> MergeCollinearEdges can get into a state where it can infinitely
> recurse. This will avoid this until we can figure out what exactly
> is going on there.
>
> Bug: b/385180591
> Bug: b/382953492
> Change-Id: I861013788b1ecd9fe7eeccdd374dbe7424cced9d
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/931947
> Commit-Queue: Jim Van Verth <jvanverth@google.com>
> Reviewed-by: Robert Phillips <robertphillips@google.com>

Bug: b/385180591
Bug: b/382953492
Change-Id: If5cfbbd4af866847e9a1a28fae33f78b57d3039d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/931832
Auto-Submit: Robert Phillips <robertphillips@google.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>