Revert "Allow lambdas with captures for SkSerialProcs/SkDeserialProcs"
This reverts commit 3d1567a97cd3956e6de85c35b1d302b1fc63a08c.

Reason for revert: Breaks the Chromium roll with the following compilation errors:

CXX obj/components/paint_preview/common/unit_tests/serial_utils_unittest.o
FAILED: obj/components/paint_preview/common/unit_tests/serial_utils_unittest.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../components/paint_preview/common/serial_utils_unittest.cc:341:10: error: indirection requires pointer operand ('SkDeserialImageProc' (aka 'function<sk_sp<SkImage> (const void *, unsigned long, void *)>') invalid)
341 |         (*(deserial_image_ctx->deserial_image_proc))(data, length, nullptr);
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

https://ci.chromium.org/ui/p/chrome/builders/try/linux-chromeos-compile-chrome/297051/overview


Original change's description:
> Allow lambdas with captures for SkSerialProcs/SkDeserialProcs
>
> See also: http://ag/24692530
>
> Canary-Android-Topic: explicit_png
> Change-Id: Id5bb9c34b7a89fdfff35a8508856d697b4c9b004
> Reviewed-on: https://skia-review.googlesource.com/c/skia/+/753496
> Owners-Override: Kevin Lubick <kjlubick@google.com>
> Reviewed-by: Leon Scroggins <scroggo@google.com>
> Commit-Queue: Kevin Lubick <kjlubick@google.com>

Change-Id: Iad025d2e01b33fbff088a8a07b43080e56c3e752
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/c/skia/+/753237
Commit-Queue: Arman Uguray <armansito@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Greg Daniel <egdaniel@google.com>