Revert "re-enable effect deserialization for flutter"
This reverts commit 798a713685a972fa8f4a258e88e15f88454bc820.

Reason for revert: try again with https://skia-review.googlesource.com/c/skia/+/163543 landed.

Original change's description:
> re-enable effect deserialization for flutter
> 
> I've got to figure this is the cause of the broken flutter roll:
> 
>     [ RUN      ] ParagraphTest.SimpleShadow
>     ../../third_party/skia/src/core/SkWriteBuffer.cpp:238: fatal error: "assert(name)"
>     ./flutter/testing/run_tests.sh: line 11: 13151 Trace/breakpoint trap   (core dumped) out/host_debug_unopt/txt_unittests --font-directory=flutter/third_party/txt/third_party/fonts
> 
> Change-Id: Idffbd203c9f790fd7613153d9f7973c7ad0a87a5
> Reviewed-on: https://skia-review.googlesource.com/c/163541
> Reviewed-by: Mike Klein <mtklein@google.com>
> Reviewed-by: Greg Daniel <egdaniel@google.com>
> Commit-Queue: Mike Klein <mtklein@google.com>

TBR=egdaniel@google.com,mtklein@google.com

Change-Id: I2d30abb1291920048a12c80ec297c0f7d279532e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true