Update patch set 2
Patch Set 2:

This broke the Flutter roll:

https://chromium-swarm.appspot.com/task?id=45f6f9bf4ffc2810

[2743/3538] CXX obj/third_party/skia/src/codec/wuffs.SkWuffsCodec.o
FAILED: obj/third_party/skia/src/codec/wuffs.SkWuffsCodec.o 
../../buildtools/linux-x64/clang/bin/clang++ -MMD -MF obj/third_party/skia/src/codec/wuffs.SkWuffsCodec.o.d -DUSE_OPENSSL=1 -DUSE_OPENSSL_CERTS=1 -DNO_TCMALLOC -DTOOLCHAIN_VERSION=bac220c15490dcf7b7d8136f75100bbc77e8d217 -DANDROID -DHAVE_SYS_UIO_H -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D__compiler_offsetof=__builtin_offsetof -Dnan=__builtin_nan -D__GNU_SOURCE=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_DISABLE_REDUCE_OPLIST_SPLITTING -DSK_LEGACY_SKCODEC_NONE_ENUM -DSK_GL -DSK_ENABLE_DUMP_GPU -DSK_DISABLE_AAA -DSK_DISABLE_READBUFFER -DSK_DISABLE_EFFECT_DESERIALIZATION -DSK_DISABLE_LEGACY_SHADERCONTEXT -DSK_DISABLE_LOWP_RASTER_PIPELINE -DSK_FORCE_RASTER_PIPELINE_BLITTER -DSK_ASSUME_GL_ES=1 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_EXPONENT=1.4 -DSK_GAMMA_CONTRAST=0.0 -DSKIA_IMPLEMENTATION=1 -DSK_HAS_WUFFS_LIBRARY -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../third_party/skia -I../../third_party/wuffs/release/c -fno-strict-aliasing -march=armv7-a -mfloat-abi=softfp -mtune=generic-armv7-a -mthumb -fPIC -pipe -fcolor-diagnostics -ffunction-sections -funwind-tables -fno-short-enums -nostdinc++ --target=arm-linux-androideabi -mfpu=neon -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -isystem../../third_party/android_tools/ndk/sources/android/support/include -isystem../../third_party/android_tools/ndk/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -fvisibility=hidden --sysroot=/mnt/pd0/s/w/ir/cache/work/flutter/src/third_party/android_tools/ndk/sysroot -Wheader-hygiene -Wstring-conversion -Wthread-safety -Oz -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -flto -g2 -Wno-unused-function -Wno-c++11-narrowing -fvisibility-inlines-hidden -std=c++17 -fno-rtti -fno-exceptions   -c ../../third_party/skia/src/codec/SkWuffsCodec.cpp -o obj/third_party/skia/src/codec/wuffs.SkWuffsCodec.o
../../third_party/skia/src/codec/SkWuffsCodec.cpp:33:2: error: "Wuffs version is too old. Upgrade to the latest version."
#error "Wuffs version is too old. Upgrade to the latest version."
 ^
1 error generated.

Patch-set: 2
CC: Gerrit User 5631 <5631@5086850b-e599-37d2-8ec8-ff16aeccbf02>
CC: Gerrit User 5641 <5641@5086850b-e599-37d2-8ec8-ff16aeccbf02>