Update patch set 3
Patch Set 3:

Looks like this breaks Housekeeper-PerCommit-CheckGeneratedFiles bot:
https://chromium-swarm.appspot.com/task?id=41360271ac51ce10&refresh=10


FAILED: obj/src/sksl/skslc.SkSLGLSLCodeGenerator.o 
c++ -MMD -MF obj/src/sksl/skslc.SkSLGLSLCodeGenerator.o.d -DSKSL_STANDALONE -DNDEBUG -I../../../cache/work/skia/src/gpu -I../../../cache/work/skia/src/sksl -fstrict-aliasing -fPIC -O3 -fdata-sections -ffunction-sections -g -Werror -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-implicit-fallthrough -Wno-unused-parameter -isystem /mnt/pd0/s/w/ir/cache/work/skia/third_party/externals/spirv-tools/include -isystem /mnt/pd0/s/w/ir/cache/work/skia/third_party/externals/spirv-tools/source -isystem /mnt/pd0/s/w/ir/build/out/Release/spirv-tools -std=c++14 -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wno-noexcept-type -c ../../../cache/work/skia/src/sksl/SkSLGLSLCodeGenerator.cpp -o obj/src/sksl/skslc.SkSLGLSLCodeGenerator.o
../../../cache/work/skia/src/sksl/SkSLGLSLCodeGenerator.cpp: In member function ‘virtual void SkSL::GLSLCodeGenerator::writeFunctionCall(const SkSL::FunctionCall&)’:
../../../cache/work/skia/src/sksl/SkSLGLSLCodeGenerator.cpp:540:48: error: ‘const class SkSL::StandaloneShaderCaps’ has no member named ‘builtinFMASupport’; did you mean ‘integerSupport’?
                 if (!fProgram.fSettings.fCaps->builtinFMASupport()) {
                                                ^~~~~~~~~~~~~~~~~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-noexcept-type’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-implicit-fallthrough’ [-Werror]
cc1plus: all warnings being treated as errors



Not sure why nothing in the CQ failed.

Patch-set: 3
CC: Gerrit User 5145 <5145@5086850b-e599-37d2-8ec8-ff16aeccbf02>